import { notFound } from "next/navigation";
import { services, type ServiceSlug } from "@/data/services";
import { regions } from "@/data/regions";
import { guides } from "@/data/allGuides";
import { getServiceDetail } from "@/data/serviceDetails";
import { getExtraServiceDetail } from "@/data/serviceDetailsExtra";
import { getMoreServiceDetail } from "@/data/serviceDetailsMore";
import { getServiceIntent } from "@/data/serviceIntent";
import { getExtraServiceIntent } from "@/data/serviceIntentExtra";
import { getServiceSeo } from "@/data/serviceSeo";

const support = { rate: "전용면적 3.3㎡당 20만원 한도", max: "최대 600만원", url: "https://www.sbiz24.kr/" };
const baseUrl = "https://busanall.vercel.app"; const inquiryUrl = "https://maxpool.olbarun.kr/";
const fallbackGuideSlugs: Partial<Record<ServiceSlug, string[]>> = {
  "kids-cafe":["restoration-scope-checklist","demolition-estimate-checklist","demolition-waste-guide"],"beauty-shop":["beauty-salon-demolition-guide","restoration-scope-checklist","demolition-estimate-checklist"],dental:["hospital-demolition-guide","restoration-scope-checklist","demolition-estimate-checklist"],pharmacy:["hospital-demolition-guide","restoration-scope-checklist","demolition-estimate-checklist"],"retail-store":["busan-store-closure-demolition-guide","landlord-restoration-dispute-checklist","demolition-cost-per-pyeong-guide"],"unmanned-store":["convenience-store-closing-demolition","restoration-scope-checklist","demolition-estimate-checklist"],mart:["convenience-store-closing-demolition","restoration-scope-checklist","demolition-waste-guide"],lodging:["restoration-scope-checklist","demolition-estimate-checklist","demolition-waste-guide"],bathhouse:["restoration-scope-checklist","demolition-estimate-checklist","partial-demolition-guide"],laundry:["restoration-scope-checklist","demolition-estimate-checklist","partial-demolition-guide"],pub:["restaurant-closing-demolition","closure-demolition-support-2026","demolition-estimate-checklist"],bakery:["cafe-closing-demolition","restaurant-closing-demolition","closure-demolition-support-2026"],"pet-shop":["restoration-scope-checklist","demolition-estimate-checklist","closure-demolition-support-2026"]};

const pointTones=["blue","orange","purple","green","cyan","rose"] as const;
function DetailIcon({type}:{type:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(type==="check")return <svg {...p}><path d="M5 12l4 4L19 6"/><path d="M4 4h16v16H4z"/></svg>;if(type==="layers")return <svg {...p}><path d="M12 3l9 5-9 5-9-5z"/><path d="M3 12l9 5 9-5M3 16l9 5 9-5"/></svg>;if(type==="access")return <svg {...p}><path d="M4 18h16M6 18V8h12v10"/><path d="M9 12h6M12 9v6"/></svg>;if(type==="restore")return <svg {...p}><path d="M4 11l8-7 8 7v9H4z"/><path d="M8 16h8M12 12v8"/></svg>;if(type==="hammer")return <svg {...p}><path d="M14 5l5 5M16 3l5 5-3 3-5-5zM13 10L5 18a2 2 0 0 0 3 3l8-8"/></svg>;if(type==="cost")return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h3M13 11h3M8 15h3M13 15h3"/></svg>;if(type==="document")return <svg {...p}><path d="M6 3h9l4 4v14H6z"/><path d="M15 3v5h4M9 12h6M9 16h6"/></svg>;if(type==="warning")return <svg {...p}><path d="M12 3l9 17H3z"/><path d="M12 9v5M12 17h.01"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="8"/><path d="M9 12l2 2 4-4"/></svg>}
function guideIconType(category:string){if(category.includes("비용"))return"cost";if(category.includes("원상복구"))return"restore";if(category.includes("지원"))return"document";if(category.includes("기초"))return"warning";return"document"}
export function generateStaticParams(){return Object.keys(services).map((slug)=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const serviceSlug=slug as ServiceSlug;const item=services[serviceSlug];if(!item)return{};const seo=getServiceSeo(serviceSlug);const title=seo?.title??`${item.primary}·원상복구`;const description=seo?.description??item.summary;return{title,description,keywords:seo?.keywords,robots:{index:true,follow:true},alternates:{canonical:`/service/${slug}`},openGraph:{title:seo?.ogTitle??title,description:seo?.ogDescription??description,url:`/service/${slug}`,type:"article"},twitter:{card:"summary",title:seo?.ogTitle??title,description:seo?.ogDescription??description}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const serviceSlug=slug as ServiceSlug;const item=services[serviceSlug];if(!item)notFound();const detail=getServiceDetail(serviceSlug)??getExtraServiceDetail(serviceSlug)??getMoreServiceDetail(serviceSlug);const intent=getServiceIntent(serviceSlug)??getExtraServiceIntent(serviceSlug);const relatedRegions=Object.entries(regions).filter(([,region])=>(region.services as readonly string[]).includes(slug)).slice(0,8);const directGuides=guides.filter((guide)=>guide.relatedServices.includes(slug)).sort((a,b)=>Number(b.category==="업종별 가이드")-Number(a.category==="업종별 가이드"));const fallbackSlugs=fallbackGuideSlugs[serviceSlug]??["demolition-cost-per-pyeong-guide","building-management-demolition-notice","restoration-scope-checklist","demolition-estimate-checklist"];const fallbackGuides=fallbackSlugs.map((guideSlug)=>guides.find((guide)=>guide.slug===guideSlug)).filter((guide):guide is (typeof guides)[number]=>Boolean(guide));const relatedGuides=[...directGuides,...fallbackGuides].filter((guide,index,list)=>list.findIndex((entry)=>entry.slug===guide.slug)===index).slice(0,5);const defaultFaq=[{q:"철거비는 무엇으로 달라지나요?",a:"면적뿐 아니라 설비, 마감재, 폐기물량, 반출조건, 작업시간과 원상복구 범위가 함께 영향을 줍니다."},{q:"사진만으로 견적이 가능한가요?",a:"간단한 범위는 사진으로 1차 확인할 수 있지만 설비·배관·반출조건이 복잡한 현장은 방문 확인이 더 정확합니다."},{q:"폐업지원금은 누구나 최대 한도를 받나요?",a:"아닙니다. 실제 지급액은 신청자격과 인정비용 등 최신 공고 기준에 따라 달라집니다."}];const faqItems=detail?.faq??defaultFaq;const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"철거서비스",item:`${baseUrl}/service`},{"@type":"ListItem",position:3,name:item.name,item:`${baseUrl}/service/${slug}`}]},{"@context":"https://schema.org","@type":"Service",name:item.primary,description:item.summary,serviceType:item.primary,areaServed:{"@type":"AdministrativeArea",name:"부산광역시"},provider:{"@type":"Organization",name:"올바른철거",url:baseUrl},url:`${baseUrl}/service/${slug}`},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqItems.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}];return <main className="page-shell">
<style>{`
.detail-tone-blue{--d-bg:#eef4ff;--d-border:#d8e5ff;--d-color:#2458d8}.detail-tone-orange{--d-bg:#fff4e8;--d-border:#f7ddbd;--d-color:#a9570a}.detail-tone-purple{--d-bg:#f5f0ff;--d-border:#e4d8ff;--d-color:#7048c8}.detail-tone-green{--d-bg:#edf9f2;--d-border:#d2efde;--d-color:#18794e}.detail-tone-cyan{--d-bg:#ecf9fb;--d-border:#cfedf1;--d-color:#087b8c}.detail-tone-rose{--d-bg:#fff0f3;--d-border:#f5d6df;--d-color:#b4234d}
.detail-point-icon,.detail-target-icon,.detail-guide-icon{display:grid;place-items:center;background:var(--d-bg);border:1px solid var(--d-border);color:var(--d-color);transition:.2s ease}.detail-point-icon{width:50px;height:50px;border-radius:15px;margin-bottom:14px}.detail-point-icon svg{width:25px;height:25px}.feature-card:hover .detail-point-icon{transform:translateY(-2px);background:var(--d-color);color:#fff}.detail-step{display:inline-flex;padding:4px 8px;border-radius:999px;background:var(--d-bg);border:1px solid var(--d-border);color:var(--d-color);font-size:10px;font-weight:850;margin-bottom:10px}.detail-target-card{position:relative;padding-left:58px}.detail-target-icon{position:absolute;left:14px;top:50%;transform:translateY(-50%);width:32px;height:32px;border-radius:10px}.detail-target-icon svg{width:18px;height:18px}.detail-guide-icon{width:44px;height:44px;border-radius:13px}.detail-guide-icon svg{width:22px;height:22px}.service-card:hover .detail-guide-icon{background:var(--d-color);color:#fff;transform:translateY(-2px)}
@media(max-width:760px){.detail-point-icon{width:46px;height:46px}.detail-point-icon svg{width:23px;height:23px}}
`}</style>
{structuredData.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>)}<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/service">철거서비스</a><span>›</span><strong>{item.name}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● 부산 업종별 철거</div><h1>{item.primary}<br/><span className="gradient-text">철거·원상복구 가이드</span></h1><p>{item.summary}</p><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a></div></header>
<section className="split"><article className="info-card"><span className="section-kicker">FIELD CHECK</span><h2>현장에서 먼저 확인할 것</h2><p>철거 범위, 설비 수량, 폐기물 반출 동선, 건물 관리규정과 임대차 원상복구 조건을 함께 확인해야 견적이 구체화됩니다.</p></article><article className="info-card"><span className="section-kicker">WHY IT VARIES</span><h2>같은 평수여도 비용은 달라집니다</h2><p>천장·벽체·바닥 재질, 설비 종류, 층수와 엘리베이터, 차량 접근성에 따라 작업량과 폐기물량이 달라질 수 있습니다.</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">CORE POINTS</span><h2>{item.name} 핵심 체크사항</h2></div><p>업종별로 실제 현장에서 차이가 나는 항목을 먼저 확인하세요.</p></div><div className="feature-grid">{item.unique.map((text,i)=>{const tone=pointTones[i%pointTones.length];const icon=["check","layers","access","restore","warning","check"][i%6];return <article className={`feature-card detail-tone-${tone}`} key={text}><span className="detail-step">POINT {i+1}</span><div className="detail-point-icon"><DetailIcon type={icon}/></div><p>{text}</p></article>})}</div></section>
{intent&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">SEARCH INTENT</span><h2>이 페이지에서 다루는 철거 범위</h2></div><p>{intent.focus}</p></div><div className="scenario-grid">{intent.differsFrom.map((entry)=><a className="scenario-card" href={`/service/${entry.slug}`} key={entry.slug}><span>비슷한 서비스 비교</span><h3>{entry.title}</h3><p>{entry.text}</p></a>)}</div></section>}
{detail&&<><section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">WHAT TO REMOVE</span><h2>{item.name}, 실제로 무엇을 철거할까?</h2></div><p>업종의 핵심 시설을 기준으로 철거·보존·이전 품목을 먼저 나누면 범위를 정하기 쉬워집니다.</p></div><div className="detail-list-grid">{detail.targets.map((text,i)=>{const tone=pointTones[i%pointTones.length];return <article className={`detail-list-card detail-target-card detail-tone-${tone}`} key={text}><span className="detail-target-icon"><DetailIcon type="hammer"/></span><span>{text}</span></article>})}</div></section><section className="section split"><article className="info-card"><span className="section-kicker">COST DRIVERS</span><h2>{item.name} 견적이 달라지는 상황</h2><ul>{detail.costDrivers.map((text)=><li key={text}>{text}</li>)}</ul></article><article className="info-card"><span className="section-kicker">SAVE FIRST</span><h2>철거 전에 따로 빼둘 것</h2><ul>{detail.salvage.map((text)=><li key={text}>{text}</li>)}</ul></article></section><section className="section"><div className="section-heading"><div><span className="section-kicker">IF THIS HAPPENS</span><h2>{item.name}에서 자주 생기는 현장 변수</h2></div><p>평수만으로는 알기 어려운 상황을 미리 확인하면 견적 범위와 작업 순서를 더 구체적으로 잡을 수 있습니다.</p></div><div className="scenario-grid">{detail.scenario.map((entry)=><article className="scenario-card" key={entry.title}><span>현장 변수</span><h3>{entry.title}</h3><p>{entry.text}</p></article>)}</div></section><section className="section split"><article className="info-card"><span className="section-kicker">RESTORATION</span><h2>원상복구에서 확인할 부분</h2><ul>{detail.restoration.map((text)=><li key={text}>{text}</li>)}</ul></article><article className="info-card"><span className="section-kicker">PHOTO ESTIMATE</span><h2>견적 전에 찍어두면 좋은 사진</h2><ol>{detail.photoChecklist.map((text)=><li key={text}>{text}</li>)}</ol><p>사진은 현장 전체 → 주요 설비 → 반출 동선 순서로 찍으면 1차 범위를 파악하기 쉽습니다.</p></article></section></>}
{relatedRegions.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">LOCAL MATCH</span><h2>{item.name}과 함께 보는 부산 지역정보</h2></div><p>같은 업종도 지역별 건물 유형, 차량 접근, 엘리베이터와 폐기물 반출 조건에 따라 작업 방식이 달라질 수 있습니다.</p></div><div className="region-link-grid">{relatedRegions.map(([regionSlug,region])=><a href={`/busan/${regionSlug}`} key={regionSlug}><strong>{region.name} {item.name}</strong><span>{region.neighborhoods.slice(0,3).join(" · ")} 현장 조건 보기</span></a>)}</div><div className="cta-row"><a className="btn btn-glass" href="/busan">부산 16개 구·군 전체 보기</a></div></section>}
<section className="section"><div className="section-heading"><div><span className="section-kicker">FIELD IMAGES</span><h2>현장 사진 영역</h2></div><p>실제 시공 사진이 확보되면 전·중·후 과정이 보이도록 교체합니다.</p></div><div className="image-grid">{[1,2,3,4].map((n)=><figure className="image-slot" key={n}><div className="placeholder"><div><strong>현장 이미지 {n}</strong><span>/public/images/services/{slug}/0{n}.webp</span></div></div><figcaption>{item.primary} 현장 이미지 {n}</figcaption></figure>)}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">READY FOR ESTIMATE</span><h2>{item.name} 견적 전에 이 6가지를 준비하세요</h2></div><p>현장 위치, 업종·면적, 층수·엘리베이터, 철거범위, 희망일정과 현장사진을 정리하면 1차 상담에서 필요한 조건을 더 빠르게 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료견적 문의하기</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a><a className="btn btn-glass" href="/guide/demolition-estimate-checklist">견적 비교 체크리스트</a></div></section>
<section className="support-box section"><span className="section-kicker">2026 CLOSURE SUPPORT</span><h2>폐업 예정이라면 공사 전에 지원제도도 확인하세요</h2><p>희망리턴패키지 점포철거비 지원은 신청자격과 인정비용, 증빙 기준이 있습니다.</p><div className="support-stats"><div><span>지원 기준</span><strong>{support.rate}</strong></div><div><span>최대 한도</span><strong>{support.max}</strong></div></div><p>실제 지원 여부와 지급액은 신청자격, 인정면적, 증빙 가능한 비용, 폐업일 및 최신 공고 기준에 따라 달라질 수 있으며 예산 소진 시 조기 종료될 수 있습니다.</p><div className="cta-row"><a className="btn btn-primary" href="/support">지원 안내 보기</a><a className="btn btn-glass" href={support.url} target="_blank" rel="noreferrer">소상공인24 확인</a></div></section>
<section className="section faq"><div className="section-heading"><div><span className="section-kicker">FAQ</span><h2>{item.primary} 자주 묻는 질문</h2></div></div>{faqItems.map((faq)=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>
{relatedGuides.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">RELATED GUIDE</span><h2>{item.name}과 함께 보면 좋은 철거 가이드</h2></div><p>업종 전용 가이드와 함께 철거비용, 원상복구, 관리실 신고, 설비 차단처럼 실제 준비 단계에서 필요한 주제를 연결했습니다.</p></div><div className="service-grid">{relatedGuides.map((guide,i)=>{const tone=pointTones[i%pointTones.length];return <a className={`service-card detail-tone-${tone}`} href={`/guide/${guide.slug}`} key={guide.slug}><div className="service-card-top"><span className="detail-guide-icon"><DetailIcon type={guideIconType(guide.category)}/></span><span className="service-card-arrow">↗</span></div><small className="section-kicker">{guide.category}</small><strong style={{marginTop:"8px"}}>{guide.title}</strong><span>{guide.description}</span></a>})}</div><div className="cta-row"><a className="btn btn-glass" href="/guide">전체 철거가이드 보기</a></div></section>}
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">RELATED INFO</span><h2>견적·원상복구 정보도 같이 확인하세요</h2></div><p>업종 정보와 현장조건을 함께 보면 실제 철거 범위를 더 구체적으로 정리할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-glass" href="/guide/demolition-cost-per-pyeong-guide">철거 평당비용 해석</a><a className="btn btn-glass" href="/guide/landlord-restoration-dispute-checklist">원상복구 분쟁 체크</a><a className="btn btn-glass" href="/guide/building-management-demolition-notice">관리실 공사신고</a><a className="btn btn-glass" href="/guide">전체 철거가이드</a></div></section>
<section className="final-cta"><div><span className="section-kicker">NEXT STEP</span><h2>{item.primary}, 현장 조건부터 정리하세요</h2><p>현장 위치, 업종·면적, 층수·엘리베이터, 철거범위, 희망일정과 사진을 준비하면 견적 상담이 더 구체적입니다.</p></div><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a></section></main>;}
