import { guideBySlug } from "@/data/allGuides";
import { guideDetailsGrowth } from "@/data/guideDetailsGrowth";
import { getGuideSearchIntent } from "@/data/guideSearchIntent";
import { services, type ServiceSlug } from "@/data/services";
import { regions } from "@/data/regions";
import ClosureSupport from "@/components/ClosureSupport";

const baseUrl="https://busanall.vercel.app";const inquiryUrl="https://maxpool.olbarun.kr/";
const growthGuideFlow:Record<string,string[]>={"busan-store-closure-demolition-guide":["landlord-restoration-dispute-checklist","demolition-cost-per-pyeong-guide","building-management-demolition-notice","utility-shutoff-before-demolition"],"demolition-cost-per-pyeong-guide":["busan-store-closure-demolition-guide","landlord-restoration-dispute-checklist","building-management-demolition-notice","utility-shutoff-before-demolition"],"landlord-restoration-dispute-checklist":["busan-store-closure-demolition-guide","demolition-cost-per-pyeong-guide","building-management-demolition-notice","utility-shutoff-before-demolition"],"building-management-demolition-notice":["utility-shutoff-before-demolition","demolition-cost-per-pyeong-guide","landlord-restoration-dispute-checklist","busan-store-closure-demolition-guide"],"utility-shutoff-before-demolition":["building-management-demolition-notice","landlord-restoration-dispute-checklist","demolition-cost-per-pyeong-guide","busan-store-closure-demolition-guide"]};
const flowLabels:Record<string,string>={"busan-store-closure-demolition-guide":"폐업 준비","demolition-cost-per-pyeong-guide":"비용 비교","landlord-restoration-dispute-checklist":"원상복구 합의","building-management-demolition-notice":"관리실 신고","utility-shutoff-before-demolition":"설비 차단"};
const tones=["blue","orange","green","purple","cyan","rose","amber","indigo"];
function GIcon({type}:{type:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(type==="cost")return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2M8 18h8"/></svg>;if(type==="restore")return <svg {...p}><path d="M3 11l9-7 9 7M5 10v10h14V10M9 20v-6h6v6"/></svg>;if(type==="utility")return <svg {...p}><path d="M13 2L6 13h6l-1 9 7-12h-6z"/></svg>;if(type==="building")return <svg {...p}><path d="M4 21V7h7v14M13 21V3h7v18M3 21h18"/><path d="M7 10h1M16 8h1M16 12h1"/></svg>;if(type==="warning")return <svg {...p}><path d="M12 3l9 17H3zM12 9v5M12 17h.01"/></svg>;if(type==="location")return <svg {...p}><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11z"/><circle cx="12" cy="10" r="2"/></svg>;if(type==="flow")return <svg {...p}><circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 6h7a3 3 0 0 1 3 3v1M17 14v1a3 3 0 0 1-3 3H7M10 15l-3 3 3 3"/></svg>;if(type==="photo")return <svg {...p}><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M8 6l1-2h6l1 2"/><circle cx="12" cy="13" r="3"/></svg>;if(type==="tool")return <svg {...p}><path d="M14 6l4-4 4 4-4 4M17 7L8 16M6 14l4 4-3 3-4-4z"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="9"/><path d="M8 12l2.5 2.5L16 9"/></svg>}
function flowIcon(slug:string){if(slug.includes("cost"))return"cost";if(slug.includes("restoration"))return"restore";if(slug.includes("utility"))return"utility";if(slug.includes("management"))return"building";return"tool"}
export default function GrowthGuide({slug}:{slug:string}){const guide=guideBySlug(slug);const detail=guideDetailsGrowth[slug];const searchIntent=getGuideSearchIntent(slug);if(!guide||!detail)return null;const relatedServices=guide.relatedServices.map(serviceSlug=>({serviceSlug,item:services[serviceSlug as ServiceSlug]})).filter(entry=>Boolean(entry.item));const relatedRegions=Object.entries(regions).map(([regionSlug,region])=>({regionSlug,region,score:region.services.filter(serviceSlug=>guide.relatedServices.includes(serviceSlug as never)).length})).filter(({score})=>score>0).sort((a,b)=>b.score-a.score).slice(0,6);const nextGuides=(growthGuideFlow[slug]??[]).map(nextSlug=>guideBySlug(nextSlug)).filter((item):item is NonNullable<ReturnType<typeof guideBySlug>>=>Boolean(item));const articleSchema={"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,mainEntityOfPage:`${baseUrl}/guide/${slug}`,author:{"@type":"Organization",name:"올바른철거",url:baseUrl},publisher:{"@type":"Organization",name:"올바른철거",url:baseUrl},about:guide.keywords};const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"철거가이드",item:`${baseUrl}/guide`},{"@type":"ListItem",position:3,name:guide.title,item:`${baseUrl}/guide/${slug}`}]};return <main className="page-shell">
<style>{`.gg-blue{--g-bg:#eef4ff;--g-border:#d8e5ff;--g-color:#2458d8}.gg-orange{--g-bg:#fff4e8;--g-border:#f7ddbd;--g-color:#a9570a}.gg-green{--g-bg:#edf9f2;--g-border:#d2efde;--g-color:#18794e}.gg-purple{--g-bg:#f5f0ff;--g-border:#e4d8ff;--g-color:#7048c8}.gg-cyan{--g-bg:#ecf9fb;--g-border:#cfedf1;--g-color:#087b8c}.gg-rose{--g-bg:#fff0f3;--g-border:#f5d6df;--g-color:#b4234d}.gg-amber{--g-bg:#fff8df;--g-border:#f2e3a8;--g-color:#8b6508}.gg-indigo{--g-bg:#eef0ff;--g-border:#daddff;--g-color:#4c51bf}.gg-icon{width:50px;height:50px;border-radius:15px;display:grid;place-items:center;background:var(--g-bg);border:1px solid var(--g-border);color:var(--g-color);margin-bottom:14px;transition:.2s ease}.gg-icon svg{width:25px;height:25px}.feature-card:hover .gg-icon,.service-card:hover .gg-icon{background:var(--g-color);color:#fff;transform:translateY(-2px) scale(1.04);box-shadow:0 8px 18px rgba(17,24,39,.1)}.gg-mini{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--g-bg);border:1px solid var(--g-border);color:var(--g-color);flex:0 0 auto}.gg-mini svg{width:18px;height:18px}.gg-list{display:flex;gap:12px;align-items:flex-start}.gg-label{display:inline-flex;align-items:center;gap:7px;padding:6px 9px;border-radius:999px;background:var(--g-bg);border:1px solid var(--g-border);color:var(--g-color);font-size:11px;font-weight:850}.gg-label svg{width:16px;height:16px}`} </style>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/><nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/guide">철거가이드</a><span>›</span><strong>{guide.category}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● {guide.category}</div><h1>{guide.title}</h1><p>{guide.description}</p><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a></div></header>
{searchIntent&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">SEARCH PURPOSE</span><h2>이 가이드는 이런 질문을 해결합니다</h2></div><p>비슷한 철거 글과 역할이 겹치지 않도록 이 페이지가 답하려는 검색 목적을 명확히 구분했습니다.</p></div><div className="split"><article className="info-card"><span className="section-kicker">PRIMARY QUESTION</span><h2>{searchIntent.primaryQuery}</h2><p>{searchIntent.goal}</p></article><article className="info-card"><span className="section-kicker">INTENT</span><h2>{searchIntent.intent}</h2><p>이 글은 위 목적을 중심으로 설명합니다. 업종별 철거범위나 다른 준비 단계가 필요하면 아래 관련 서비스와 다음 단계 가이드에서 이어서 확인하세요.</p></article></div></section>}
<section className="section"><div className="section-heading"><div><span className="section-kicker">KEY GUIDE</span><h2>먼저 확인할 핵심 기준</h2></div><p>실제 철거를 결정하기 전에 순서대로 확인하면 좋은 내용을 정리했습니다.</p></div><div className="feature-grid">{guide.sections.map((section,index)=>{const tone=tones[index%tones.length];return <article className={`feature-card gg-${tone}`} key={section.title}><div className="gg-icon"><GIcon type={["document","tool","warning","flow"][index%4]}/></div><h2>{section.title}</h2><p>{section.body}</p></article>})}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">FIELD CHECKLIST</span><h2>현장에서 확인할 체크리스트</h2></div><p>사진과 함께 정리해두면 견적과 원상복구 범위를 설명하기 쉬워집니다.</p></div><div className="detail-list-grid">{detail.checklist.map((text,index)=>{const tone=tones[index%tones.length];return <article className={`detail-list-card gg-list gg-${tone}`} key={text}><span className="gg-mini"><GIcon type="check"/></span><span>{text}</span></article>})}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">COMMON MISTAKES</span><h2>자주 놓치는 부분</h2></div><p>공사 후 범위를 다시 협의하거나 재작업하는 상황을 줄이기 위해 미리 확인하세요.</p></div><div className="scenario-grid">{detail.mistakes.map((item,index)=><article className={`scenario-card gg-${tones[(index+5)%tones.length]}`} key={item.title}><span className="gg-mini"><GIcon type="warning"/></span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">WORK FLOW</span><h2>준비 순서</h2></div><p>현장마다 세부 조건은 다르지만 확인 순서를 잡는 기준으로 사용할 수 있습니다.</p></div><div className="process-grid">{detail.timeline.map((step,index)=><article className={`process-step gg-${tones[(index+2)%tones.length]}`} key={step.title}><span className="gg-mini"><GIcon type="flow"/></span><b>{step.label}</b><strong>{step.title}</strong><p>{step.text}</p></article>)}</div></section>
<section className="section split"><article className="info-card"><span className="section-kicker">ASK BEFORE QUOTE</span><h2>견적 전에 물어볼 질문</h2><ul>{detail.questions.map(question=><li key={question}>{question}</li>)}</ul></article><article className="info-card"><span className="section-kicker">PHOTO TIP</span><h2>현장사진 준비 방법</h2><div className="gg-icon gg-cyan"><GIcon type="photo"/></div><p>점포 전체, 천장·벽·바닥, 주요 설비, 출입구, 계단·승강기와 차량 상차 위치를 순서대로 촬영하세요.</p><p>철거하지 않고 남길 시설도 별도로 촬영하면 존치 범위를 전달하기 쉽습니다.</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">VISUAL GUIDE</span><h2>현장사진·체크 이미지 영역</h2></div><p>실제 현장사진과 체크리스트 이미지가 확보되면 이 가이드 주제에 맞는 이미지로 교체할 수 있도록 영역을 준비했습니다.</p></div><div className="image-grid">{[1,2,3,4].map(n=><figure className="image-slot" key={n}><div className="placeholder"><strong>가이드 이미지 {n}</strong><span>/public/images/guides/{slug}/{String(n).padStart(2,"0")}.webp</span></div></figure>)}</div></section>
{slug==="busan-store-closure-demolition-guide"&&<ClosureSupport serviceName="상가 폐업철거"/>}
{nextGuides.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">NEXT STEP GUIDES</span><h2>이어서 확인할 준비 단계</h2></div><p>한 주제만 보고 끝내지 않도록 비용·원상복구·관리실·설비·폐업 준비를 실제 진행 흐름에 맞춰 연결했습니다.</p></div><div className="service-grid">{nextGuides.map((nextGuide,index)=>{const tone=tones[index%tones.length];return <a className={`service-card gg-${tone}`} href={`/guide/${nextGuide.slug}`} key={nextGuide.slug}><div className="service-card-top"><span className="gg-icon"><GIcon type={flowIcon(nextGuide.slug)}/></span><span className="service-card-arrow">↗</span></div><span className="gg-label"><GIcon type={flowIcon(nextGuide.slug)}/>{flowLabels[nextGuide.slug]??nextGuide.category}</span><strong style={{marginTop:"8px"}}>{nextGuide.title}</strong><span>{nextGuide.description}</span></a>})}</div><div className="cta-row"><a className="btn btn-glass" href="/guide/demolition-estimate-checklist">견적 비교 체크리스트</a><a className="btn btn-glass" href="/support">2026 폐업지원 확인</a></div></section>}
{relatedServices.length>0&&<section className="section"><div className="section-heading"><div><span className="section-kicker">RELATED SERVICE</span><h2>함께 확인할 철거서비스</h2></div><p>가이드의 공통 기준을 실제 업종별 설비와 원상복구 조건에 연결해 확인하세요.</p></div><div className="service-grid">{relatedServices.map(({serviceSlug,item},index)=>{const tone=tones[(index+1)%tones.length];return <a className={`service-card gg-${tone}`} href={`/service/${serviceSlug}`} key={serviceSlug}><div className="service-card-top"><span className="gg-icon"><GIcon type="tool"/></span><span className="service-card-arrow">↗</span></div><strong>{item.name}</strong><span>{item.summary}</span></a>})}</div></section>}
{relatedRegions.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">LOCAL GUIDE</span><h2>부산 지역별 현장 조건도 함께 확인하세요</h2></div><p>같은 준비 주제라도 층수, 골목 진입, 승강기, 관리규정과 차량 상차 조건에 따라 실제 작업 방식이 달라질 수 있습니다.</p></div><div className="service-grid">{relatedRegions.map(({regionSlug,region},index)=>{const tone=tones[(index+4)%tones.length];return <a className={`service-card gg-${tone}`} href={`/busan/${regionSlug}`} key={regionSlug}><div className="service-card-top"><span className="gg-icon"><GIcon type="location"/></span><span className="service-card-arrow">↗</span></div><strong>{region.name} 철거</strong><span>{region.neighborhoods.slice(0,3).join(" · ")} 등 지역별 반출·건물 조건 확인</span></a>})}</div><div className="cta-row"><a className="btn btn-glass" href="/busan">부산 16개 구·군 전체 보기</a></div></section>}
<section className="final-cta"><div><span className="section-kicker">FIELD CHECK</span><h2>기준을 확인했다면<br/>내 현장 조건을 정리하세요</h2><p>위치, 업종·면적, 층수·승강기, 철거범위, 희망일정과 현장사진을 준비하면 상담 시 범위를 더 구체적으로 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/guide">전체 가이드 보기</a></div></section></main>;}