"use client";

import {FormEvent,useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";

const districts=["강서구","금정구","기장군","남구","동구","동래구","부산진구","북구","사상구","사하구","서구","수영구","연제구","영도구","중구","해운대구"];
const businesses=["상가","식당","카페","사무실","학원","병원·의원","공장","창고","미용실","주점","주택","기타"];

export default function HomeEstimateForm(){
 const pathname=usePathname();const ref=useRef<HTMLElement|null>(null);const [sending,setSending]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(pathname!=="/")return;const el=ref.current;const rail=document.querySelector(".seo-image-section");const hero=document.querySelector(".home-hero");if(el){if(rail?.parentElement)rail.insertAdjacentElement("afterend",el);else if(hero?.parentElement)hero.insertAdjacentElement("afterend",el)}},[pathname]);
 if(pathname!=="/")return null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const form=e.currentTarget;const fd=new FormData(form);if(!fd.get("closureReady")||!fd.get("privacy")||!fd.get("thirdParty")){setMessage("필수 동의 항목을 확인해 주세요.");return}setSending(true);try{const payload=Object.fromEntries(fd.entries());const r=await fetch("/api/estimate-inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data?.message||"접수 중 오류가 발생했습니다.");setMessage("상담 신청이 접수되었습니다. 확인 후 연락드리겠습니다.");form.reset()}catch(err){setMessage(err instanceof Error?err.message:"접수 중 오류가 발생했습니다.")}finally{setSending(false)}}
 return <section ref={ref} className="estimate-lead" aria-labelledby="estimate-lead-title"><div className="estimate-lead-head"><span>BUSAN FREE ESTIMATE</span><h2 id="estimate-lead-title">부산 철거 무료 견적 상담 신청</h2><p><b>*표시된 항목은 상담 진행을 위해 꼭 필요한 정보</b>이며, 입력된 정보는 상담 목적 외에는 사용하지 않습니다.</p></div><form onSubmit={submit} className="estimate-form"><div className="estimate-grid"><label><span>이름<em>*</em></span><input name="name" required maxLength={30} placeholder="이름" autoComplete="name"/></label><label><span>지역<em>*</em></span><select name="region" required defaultValue=""><option value="" disabled>부산 지역구 선택</option>{districts.map(v=><option key={v} value={v}>부산 {v}</option>)}</select></label><label><span>전화번호<em>*</em></span><input name="phone" required inputMode="tel" maxLength={20} placeholder="010-0000-0000" autoComplete="tel"/></label><label><span>업종<em>*</em></span><select name="business" required defaultValue=""><option value="" disabled>업종 선택</option>{businesses.map(v=><option key={v}>{v}</option>)}</select></label></div><div className="estimate-agreements"><label><input type="checkbox" name="closureReady" value="yes" required/><span><b>(필수)</b> 현재 폐업 준비 중이거나 철거·원상복구 예정인 분에 한해 상담이 가능합니다.</span></label><label><input type="checkbox" name="privacy" value="yes" required/><span><b>(필수)</b> 개인정보의 수집 및 이용 <a href="/privacy/estimate-collection" target="_blank" rel="noopener">[자세히 보기]</a></span></label><label><input type="checkbox" name="thirdParty" value="yes" required/><span><b>(필수)</b> 개인정보의 제3자 제공 <a href="/privacy/estimate-third-party" target="_blank" rel="noopener">[자세히 보기]</a></span></label><label><input type="checkbox" name="marketing" value="yes"/><span><b>(선택)</b> 개인정보의 마케팅 활용 동의 <a href="/privacy/estimate-marketing" target="_blank" rel="noopener">[자세히 보기]</a></span></label></div><button disabled={sending} type="submit">{sending?"상담 신청 접수 중...":"내 철거 비용 확인하기"}</button>{message&&<p className="estimate-result" role="status">{message}</p>}<input type="text" name="website" tabIndex={-1} autoComplete="off" className="estimate-hp" aria-hidden="true"/></form><style jsx>{`
.estimate-lead{width:min(1120px,calc(100% - 40px));margin:46px auto;padding:0 0 4px}.estimate-lead-head{text-align:center;margin-bottom:28px}.estimate-lead-head>span{display:block;color:#315cff;font-size:11px;font-weight:900;letter-spacing:.16em;margin-bottom:8px}.estimate-lead-head h2{margin:0;color:#172033;font-size:34px;letter-spacing:-.045em}.estimate-lead-head p{margin:12px 0 0;color:#667085;font-size:13px}.estimate-lead-head p b{color:#344054}.estimate-form{border:2px solid #5d7cff;border-radius:4px;background:#fff;padding:46px 56px 48px;box-shadow:0 12px 34px rgba(49,92,255,.05)}.estimate-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px 38px;padding-bottom:22px;border-bottom:1px solid #e8ecf2}.estimate-grid label{display:grid;grid-template-columns:72px 1fr;align-items:center;gap:10px}.estimate-grid label>span{font-size:13px;font-weight:800;color:#25324a}.estimate-grid em{font-style:normal;color:#ef4444}.estimate-grid input,.estimate-grid select{width:100%;height:44px;border:1px solid #d6dbe3;background:#fff;padding:0 14px;color:#344054;font-size:14px;outline:none}.estimate-grid input:focus,.estimate-grid select:focus{border-color:#4b6fff;box-shadow:0 0 0 3px rgba(75,111,255,.1)}.estimate-agreements{display:grid;gap:12px;padding:22px 24px 24px}.estimate-agreements label{display:flex;align-items:flex-start;gap:9px;color:#344054;font-size:12.5px;line-height:1.5}.estimate-agreements input{width:16px;height:16px;margin-top:1px;accent-color:#4b6fff}.estimate-agreements b{color:#202b3c}.estimate-agreements a{color:#315cff;text-decoration:none}.estimate-form button{width:100%;height:54px;border:0;border-radius:999px;background:linear-gradient(90deg,#4b6fff,#4262ee);color:#fff;font-size:17px;font-weight:900;cursor:pointer}.estimate-form button:disabled{opacity:.65;cursor:wait}.estimate-result{text-align:center;margin:14px 0 0;color:#315cff;font-size:13px;font-weight:800}.estimate-hp{position:absolute!important;left:-9999px!important;width:1px!important;height:1px!important;opacity:0!important}@media(max-width:760px){.estimate-lead{width:min(100% - 24px,560px);margin:28px auto}.estimate-lead-head h2{font-size:26px}.estimate-lead-head p{font-size:12px;line-height:1.65}.estimate-form{padding:24px 16px 26px}.estimate-grid{grid-template-columns:1fr;gap:12px}.estimate-grid label{grid-template-columns:68px 1fr}.estimate-agreements{padding:20px 4px}.estimate-form button{height:52px;font-size:16px}}
`}</style></section>
}