import { notFound } from "next/navigation";
import { regions, type RegionSlug } from "@/data/regions";
import { services, type ServiceSlug } from "@/data/services";
import { guides } from "@/data/allGuides";
import { getRegionDetail } from "@/data/regionDetails";
import { getRegionSeo } from "@/data/regionSeo";

const baseUrl="https://www.parcelout.kr"; const inquiryUrl="https://maxpool.olbarun.kr/";
const universalGuideSlugs=["demolition-cost-per-pyeong-guide","landlord-restoration-dispute-checklist","building-management-demolition-notice","utility-shutoff-before-demolition"] as const;
const serviceTone: Record<string,string>={"commercial-store":"blue",restaurant:"orange",cafe:"amber",office:"cyan",academy:"indigo",hospital:"green",factory:"slate",interior:"rose",lodging:"purple",pharmacy:"green",dental:"sky",mart:"orange",warehouse:"slate",house:"green",apartment:"indigo",partial:"rose"};
function CardIcon({type}:{type:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
if(["restaurant","cafe"].includes(type))return <svg {...p}><path d="M6 4v7M3 4v4a3 3 0 0 0 6 0V4M6 11v9"/><path d="M16 4v16M16 4c3 1 4 4 4 7h-4"/></svg>;
if(["hospital","pharmacy","dental"].includes(type))return <svg {...p}><path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6z"/></svg>;
if(["factory","warehouse"].includes(type))return <svg {...p}><path d="M3 21V10l6 3V9l6 3V6l6 4v11z"/><path d="M7 17h2M12 17h2M17 17h2"/></svg>;
if(["house","apartment","lodging"].includes(type))return <svg {...p}><path d="M3 11l9-8 9 8v10H3z"/><path d="M9 21v-6h6v6"/></svg>;
if(type==="academy")return <svg {...p}><path d="M4 5h7a3 3 0 0 1 3 3v11a3 3 0 0 0-3-3H4z"/><path d="M20 5h-3a3 3 0 0 0-3 3v11a3 3 0 0 1 3-3h3z"/></svg>;
if(type==="office")return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="1"/><path d="M9 7h2M13 7h2M9 11h2M13 11h2M10 21v-4h4v4"/></svg>;
if(type==="interior"||type==="partial")return <svg {...p}><path d="M14 5l5 5M16 3l5 5-3 3-5-5zM13 10L5 18a2 2 0 0 0 3 3l8-8"/></svg>;
return <svg {...p}><path d="M4 10h16v10H4z"/><path d="M3 10l2-5h14l2 5"/><path d="M8 20v-5h4v5"/></svg>}
function GuideIcon({slug}:{slug:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(slug.includes("cost"))return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2"/></svg>;if(slug.includes("restoration")||slug.includes("landlord"))return <svg {...p}><path d="M3 11l9-8 9 8v10H3z"/><path d="M9 21v-6h6v6"/></svg>;if(slug.includes("management"))return <svg {...p}><path d="M5 21V4h10v17M15 9h4v12"/><path d="M8 8h2M8 12h2M17 13h1"/></svg>;if(slug.includes("utility"))return <svg {...p}><path d="M13 2L6 13h5l-1 9 8-12h-5z"/></svg>;return <svg {...p}><path d="M6 3h9l4 4v14H6z"/><path d="M15 3v5h4M9 12h6M9 16h5"/></svg>}
function PointIcon({index}:{index:number}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(index%3===0)return <svg {...p}><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11z"/><circle cx="12" cy="10" r="2"/></svg>;if(index%3===1)return <svg {...p}><path d="M4 20V7h6v13M14 20V4h6v16"/><path d="M3 20h18"/></svg>;return <svg {...p}><path d="M4 18h16M6 14h12M8 10h8"/><path d="M5 18l3-8M19 18l-3-8"/></svg>}
export function generateStaticParams(){return Object.keys(regions).map((slug)=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const regionSlug=slug as RegionSlug;const region=regions[regionSlug];if(!region)return{};const seo=getRegionSeo(regionSlug);return{title:seo.title,description:seo.description,keywords:seo.keywords,robots:{index:true,follow:true},alternates:{canonical:`/busan/${slug}`},openGraph:{title:seo.ogTitle,description:seo.ogDescription,url:`/busan/${slug}`,type:"website",locale:"ko_KR"},twitter:{card:"summary",title:seo.ogTitle,description:seo.ogDescription}};}
export default async function RegionPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const regionSlug=slug as RegionSlug;const region=regions[regionSlug];if(!region)notFound();const detail=getRegionDetail(regionSlug);
const validServices=region.services.map((serviceSlug)=>({serviceSlug,item:services[serviceSlug as ServiceSlug]})).filter((entry)=>Boolean(entry.item));
const universalGuides=universalGuideSlugs.map((guideSlug)=>guides.find((guide)=>guide.slug===guideSlug)).filter((guide):guide is NonNullable<typeof guide>=>Boolean(guide));
const industryGuides=guides.map((guide)=>({guide,score:guide.relatedServices.filter((serviceSlug)=>(region.services as readonly string[]).includes(serviceSlug)).length})).filter(({guide,score})=>score>0&&!universalGuideSlugs.includes(guide.slug as typeof universalGuideSlugs[number])).sort((a,b)=>b.score-a.score).slice(0,2).map(({guide})=>guide);
const relatedGuides=[...universalGuides,...industryGuides].slice(0,6);
const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"부산지역",item:`${baseUrl}/busan`},{"@type":"ListItem",position:3,name:region.name,item:`${baseUrl}/busan/${slug}`}]},{"@context":"https://schema.org","@type":"Service",name:region.primary,description:region.summary,serviceType:"철거·원상복구",areaServed:{"@type":"AdministrativeArea",name:`부산광역시 ${region.name}`},provider:{"@type":"Organization",name:"올바른철거",url:baseUrl},url:`${baseUrl}/busan/${slug}`},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:detail.faq.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}];
return <main className="page-shell"><style>{`
.detail-tone-blue{--d-bg:#eef4ff;--d-border:#d8e5ff;--d-color:#2458d8}.detail-tone-orange{--d-bg:#fff4e8;--d-border:#f7ddbd;--d-color:#a9570a}.detail-tone-amber{--d-bg:#fff8df;--d-border:#f2e3a8;--d-color:#8b6508}.detail-tone-cyan{--d-bg:#ecf9fb;--d-border:#cfedf1;--d-color:#087b8c}.detail-tone-indigo{--d-bg:#eef0ff;--d-border:#daddff;--d-color:#4c51bf}.detail-tone-green{--d-bg:#edf9f2;--d-border:#d2efde;--d-color:#18794e}.detail-tone-slate{--d-bg:#f1f4f7;--d-border:#dde3ea;--d-color:#475467}.detail-tone-rose{--d-bg:#fff0f3;--d-border:#f5d6df;--d-color:#b4234d}.detail-tone-purple{--d-bg:#f5f0ff;--d-border:#e4d8ff;--d-color:#7048c8}.detail-tone-sky{--d-bg:#edf8ff;--d-border:#d2ecfb;--d-color:#0875a5}
.region-detail-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:var(--d-bg);border:1px solid var(--d-border);color:var(--d-color);transition:.2s ease}.region-detail-icon svg{width:25px;height:25px}.service-card:hover .region-detail-icon{transform:translateY(-2px);background:var(--d-color);color:#fff}.local-point-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:#eef4ff;color:#2458d8;border:1px solid #d8e5ff;margin-bottom:13px}.local-point-icon svg{width:22px;height:22px}.local-check-number{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#edf8ff;color:#0875a5;font-size:11px;font-weight:850}
`}</style>{structuredData.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>)}
<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/busan">부산지역</a><span>›</span><strong>{region.name}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● 부산 지역별 철거</div><h1>{region.primary}<br/><span className="gradient-text">현장 조건 가이드</span></h1><p>{region.summary}</p><div className="hero-points">{region.neighborhoods.map((n)=><span key={n}>{n}</span>)}</div><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a><a className="btn btn-glass" href="/support">폐업지원금 확인</a></div></header>
<section className="split"><article className="info-card"><span className="section-kicker">LOCAL FOCUS</span><h2>{region.name}에서 먼저 볼 기준</h2><p>{detail.focus}</p></article><article className="info-card"><span className="section-kicker">BUILDING RULE</span><h2>건물 규정과 반출조건 확인</h2><p>작업 가능 시간, 공용부 보양, 승강기 사용조건, 차량 진입과 폐기물 상차 위치는 같은 지역 안에서도 현장마다 달라질 수 있습니다.</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL POINTS</span><h2>{region.name} 철거에서 중요한 점</h2></div><p>지역명을 반복하기보다 실제 작업에 영향을 주는 현장 요소를 정리했습니다.</p></div><div className="feature-grid">{region.points.map((point,i)=><article className="feature-card" key={point}><div className="local-point-icon"><PointIcon index={i}/></div><p>{point}</p></article>)}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">FIELD CHECKLIST</span><h2>{region.name} 현장에서 확인할 항목</h2></div><p>견적 전 사진과 현장 확인에서 이 항목을 먼저 보면 반출·보양·설비 조건을 구체적으로 정리하기 쉽습니다.</p></div><div className="detail-list-grid">{detail.fieldChecks.map((text,i)=><article className="detail-list-card" key={text}><b className="local-check-number">{String(i+1).padStart(2,"0")}</b><span>{text}</span></article>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL SCENARIOS</span><h2>{region.name}에서 이런 현장이라면?</h2></div><p>지역별 건물과 도로 조건이 철거 방식에 어떤 영향을 줄 수 있는지 상황별로 정리했습니다.</p></div><div className="scenario-grid">{detail.scenarios.map((entry)=><article className="scenario-card" key={entry.title}><span>현장 변수</span><h3>{entry.title}</h3><p>{entry.text}</p></article>)}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">NEIGHBORHOOD CHECK</span><h2>{region.neighborhoods.slice(0,3).join(" · ")} 등 현장별 확인사항</h2></div><p>같은 {region.name} 안에서도 건물 연식, 도로 폭, 주차와 승강기 조건은 현장마다 다릅니다. 동네명만으로 비용을 정하기보다 실제 반출 조건을 함께 확인하세요.</p></div><div className="link-cloud" aria-label={`${region.name} 주요 동네`}>{region.neighborhoods.map((name)=><span className="info-chip" key={name}>{name} 현장</span>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL SERVICES</span><h2>{region.name}에서 많이 확인하는 철거 유형</h2></div><p>지역 조건과 함께 업종별 설비·원상복구 범위를 확인하세요.</p></div><div className="service-grid">{validServices.map(({serviceSlug,item})=>{const tone=serviceTone[serviceSlug]??"blue";return <a className={`service-card detail-tone-${tone}`} href={`/service/${serviceSlug}`} key={serviceSlug}><div className="service-card-top"><span className="region-detail-icon"><CardIcon type={serviceSlug}/></span><span className="service-card-arrow">↗</span></div><strong>{item.name}</strong><span>{item.summary}</span></a>})}</div></section>
{relatedGuides.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">PREPARE BY INTENT</span><h2>{region.name} 철거 전에 순서대로 확인하세요</h2></div><p>지역별 업종 정보뿐 아니라 실제 견적에 공통으로 영향을 주는 비용 → 원상복구 → 관리실 → 설비 차단 기준과 이 지역의 업종 가이드를 함께 연결했습니다.</p></div><div className="service-grid">{relatedGuides.map((guide,i)=>{const tones=["blue","purple","orange","green","cyan","indigo"];const tone=tones[i%tones.length];return <a className={`service-card detail-tone-${tone}`} href={`/guide/${guide.slug}`} key={guide.slug}><div className="service-card-top"><span className="region-detail-icon"><GuideIcon slug={guide.slug}/></span><span className="service-card-arrow">↗</span></div><strong>{guide.title}</strong><span>{guide.description}</span></a>})}</div></section>}
<section className="section"><div className="section-heading"><div><span className="section-kicker">READY FOR ESTIMATE</span><h2>{region.name} 현장정보를 정리했다면 견적을 준비하세요</h2></div><p>현장 위치, 업종·면적, 층수·엘리베이터, 철거범위, 일정과 사진을 준비하면 상담이 더 구체적입니다.</p></div><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지 확인</a><a className="btn btn-glass" href="/guide/demolition-estimate-checklist">견적 비교 체크리스트</a></div></section>
<section className="section faq"><div className="section-heading"><div><span className="section-kicker">FAQ</span><h2>{region.name} 철거 자주 묻는 질문</h2></div><p>지역별 현장 상담 전에 자주 확인하는 내용을 정리했습니다.</p></div>{detail.faq.map((faq)=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>
<section className="final-cta"><div><span className="section-kicker">LOCAL ESTIMATE</span><h2>{region.name} 현장 조건을 확인했다면<br/>실제 철거범위를 상담하세요</h2><p>현장사진과 기본정보를 준비하면 작업범위와 원상복구 항목을 더 구체적으로 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">준비정보 6가지</a></div></section></main>;}