import { notFound } from "next/navigation";
import HomeEstimateForm from "@/components/HomeEstimateForm";
import { regions, type RegionSlug } from "@/data/regions";
import { services, type ServiceSlug } from "@/data/services";
import { guides } from "@/data/allGuides";
import { getRegionDetail } from "@/data/regionDetails";
import { getRegionSeo } from "@/data/regionSeo";
import { isIndexableRegion } from "@/data/indexing";
import { isIndexableGuide } from "@/data/guideIndexing";

const baseUrl="https://www.lastwar.co.kr"; const inquiryUrl="https://maxpool.olbarun.kr/";
const universalGuideSlugs=["demolition-estimate-checklist","restoration-scope-checklist","demolition-waste-guide"] as const;
const serviceTone: Record<string,string>={"commercial-store":"blue",restaurant:"orange",cafe:"amber",office:"cyan",academy:"indigo",hospital:"green",factory:"slate",interior:"rose",lodging:"purple",pharmacy:"green",dental:"sky",mart:"orange",warehouse:"slate",house:"green",apartment:"indigo",partial:"rose"};
const haeundaeImages=[
  {src:"/images/busan/haeundae/haeundae-office-demolition-final.webp",alt:"고층 사무실의 파티션과 천장 설비 철거 검토 이미지",caption:"센텀·우동 사무실: 승강기 예약과 전기·통신설비 구분"},
  {src:"/images/busan/haeundae/haeundae-restaurant-demolition.webp",alt:"음식점 주방설비 철거 검토 이미지",caption:"중동 음식점: 후드·덕트와 급배수 연결구간 확인"},
  {src:"/images/busan/haeundae/haeundae-cafe-demolition.webp",alt:"카페 내부 철거 검토 이미지",caption:"좌동 카페: 바닥·카운터·간판 원상복구 범위 확인"},
  {src:"/images/busan/haeundae/haeundae-interior-demolition.webp",alt:"상가 내부 마감 철거 검토 이미지",caption:"재송동 상가: 공용부 보양과 폐기물 반출 동선 확인"}
];
const namImages=[
  {src:"/images/busan/nam/nam-office-demolition.webp",alt:"사무실 내부 철거 유형 참고 이미지",caption:"문현동 업무시설: 파티션·전산배선과 공용부 보양"},
  {src:"/images/busan/nam/nam-store-demolition-corrected.webp",alt:"상가 내부 철거 유형 참고 이미지",caption:"대연동 상가: 간판·바닥 마감의 원상복구 범위"},
  {src:"/images/busan/nam/nam-restaurant-demolition.webp",alt:"음식점 철거 유형 참고 이미지",caption:"대연·용호 상권: 주방설비와 급배수 차단"},
  {src:"/images/busan/nam/nam-interior-demolition.webp",alt:"내부 마감 철거 유형 참고 이미지",caption:"용당동 등 주거지 인접 현장: 반출동선과 작업시간"}
];
const sahaImages=[
  {src:"/images/busan/saha/saha-restaurant-demolition.webp",alt:"음식점 철거 유형 참고 이미지",caption:"하단동 음식점: 후드·덕트·급배수 철거 범위"},
  {src:"/images/busan/saha/saha-academy-demolition.webp",alt:"학원 철거 유형 참고 이미지",caption:"하단권 학원: 칸막이와 전기·통신 배선 구분"},
  {src:"/images/busan/saha/saha-factory-demolition.webp",alt:"공장 철거 유형 참고 이미지",caption:"장림동 산업시설: 생산설비·랙·배관 존치 여부"},
  {src:"/images/busan/saha/saha-interior-demolition.webp",alt:"내부 철거 유형 참고 이미지",caption:"괴정·다대동 현장: 진입로와 폐기물 상차 위치"}
];
const gangseoImages=[
  {src:"/images/busan/gangseo/gangseo-commercial-store-demolition-03.webp",alt:"상가 내부 철거 유형 참고 이미지",caption:"명지동 상가: 기본마감과 임차인 시설 구분"},
  {src:"/images/busan/gangseo/gangseo-factory-demolition-01.webp",alt:"공장 설비 철거 유형 참고 이미지",caption:"녹산동 산업시설: 전력·배관 차단과 설비 존치"},
  {src:"/images/busan/gangseo/gangseo-warehouse-demolition-02.webp",alt:"창고 철거 유형 참고 이미지",caption:"신호동 창고: 랙·대형 폐기물과 상차 동선"},
  {src:"/images/busan/gangseo/gangseo-interior-demolition-05.webp",alt:"내부 마감 철거 유형 참고 이미지",caption:"대저동 등 현장: 출입문 폭과 차량 진입조건"}
];
const bukImages=[
  {src:"/images/busan/buk/buk-commercial-store-demolition-01.webp",alt:"다층 상가 철거 유형 참고 이미지",caption:"덕천동 상가: 승강기 규격과 계단 반출 가능 여부"},
  {src:"/images/busan/buk/buk-beauty-salon-demolition-04.webp",alt:"미용실 철거 유형 참고 이미지",caption:"화명동 생활상가: 급배수·거울·칸막이 복구 범위"},
  {src:"/images/busan/buk/buk-commercial-store-demolition-03.webp",alt:"점포 내부 철거 유형 참고 이미지",caption:"구포동 점포: 출입문 폭과 폐기물 소형 운반"},
  {src:"/images/busan/buk/buk-interior-demolition-05.webp",alt:"내부 마감 철거 유형 참고 이미지",caption:"만덕동 골목 현장: 차량 정차와 상차 위치"}
];
const dongImages=[
  {src:"/images/busan/dong/dong-lodging-demolition-01.webp",alt:"숙박시설 철거 유형 참고 이미지",caption:"초량동 숙박시설: 객실·욕실과 공용설비 구분"},
  {src:"/images/busan/dong/dong-commercial-store-demolition-03.webp",alt:"상가 철거 유형 참고 이미지",caption:"범일동 점포: 인접 영업점 보호와 공용통로 보양"},
  {src:"/images/busan/dong/dong-restaurant-demolition-02.webp",alt:"음식점 철거 유형 참고 이미지",caption:"도심 음식점: 주방 덕트와 급배수 연결구간"},
  {src:"/images/busan/dong/dong-interior-demolition-05.webp",alt:"내부 마감 철거 유형 참고 이미지",caption:"수정·좌천동 노후 건물: 기존 배관·전기 구분"}
];
const dongnaeImages=[
  {src:"/images/busan/dongnae/dongnae-commercial-store-demolition.webp",alt:"동래구 상가 철거"},
  {src:"/images/busan/dongnae/dongnae-academy-demolition.webp",alt:"동래구 학원 철거"},
  {src:"/images/busan/dongnae/dongnae-hospital-demolition.webp",alt:"동래구 병원 철거"},
  {src:"/images/busan/dongnae/dongnae-office-demolition.webp",alt:"동래구 사무실 철거"},
  {src:"/images/busan/dongnae/dongnae-interior-demolition.webp",alt:"동래구 인테리어 철거"}
];
function CardIcon({type}:{type:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
if(["restaurant","cafe"].includes(type))return <svg {...p}><path d="M6 4v7M3 4v4a3 3 0 0 0 6 0V4M6 11v9"/><path d="M16 4v16M16 4c3 1 4 4 4 7h-4"/></svg>;
if(["hospital","pharmacy","dental"].includes(type))return <svg {...p}><path d="M9 3h6v6h6v6H9v-6H3V9h6z"/></svg>;
if(["factory","warehouse"].includes(type))return <svg {...p}><path d="M3 21V10l6 3V9l6 3V6l6 4v11z"/><path d="M7 17h2M12 17h2M17 17h2"/></svg>;
if(["house","apartment","lodging"].includes(type))return <svg {...p}><path d="M3 11l9-8 9 8v10H3z"/><path d="M9 21v-6h6v6"/></svg>;
if(type==="academy")return <svg {...p}><path d="M4 5h7a3 3 0 0 1 3 3v11a3 3 0 0 0-3-3H4z"/><path d="M20 5h-3a3 3 0 0 0-3 3v11a3 3 0 0 1 3-3h3z"/></svg>;
if(type==="office")return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="1"/><path d="M9 7h2M13 7h2M9 11h2M13 11h2M10 21v-4h4v4"/></svg>;
if(type==="interior"||type==="partial")return <svg {...p}><path d="M14 5l5 5M16 3l5 5-3 3-5-5zM13 10L5 18a2 2 0 0 0 3 3l8-8"/></svg>;
return <svg {...p}><path d="M4 10h16v10H4z"/><path d="M3 10l2-5h14l2 5"/><path d="M8 20v-5h4v5"/></svg>}
function GuideIcon({slug}:{slug:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(slug.includes("cost"))return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2"/></svg>;if(slug.includes("restoration")||slug.includes("landlord"))return <svg {...p}><path d="M3 11l9-8 9 8v10H3z"/><path d="M9 21v-6h6v6"/></svg>;if(slug.includes("management"))return <svg {...p}><path d="M5 21V4h10v17M15 9h4v12"/><path d="M8 8h2M8 12h2M17 13h1"/></svg>;if(slug.includes("utility"))return <svg {...p}><path d="M13 2L6 13h5l-1 9 8-12h-5z"/></svg>;return <svg {...p}><path d="M6 3h9l4 4v14H6z"/><path d="M15 3v5h4M9 12h6M9 16h5"/></svg>}
function PointIcon({index}:{index:number}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(index%3===0)return <svg {...p}><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11z"/><circle cx="12" cy="10" r="2"/></svg>;if(index%3===1)return <svg {...p}><path d="M4 20V7h6v13M14 20V4h6v16"/><path d="M3 20h18"/></svg>;return <svg {...p}><path d="M4 18h16M6 14h12M8 10h8"/><path d="M5 18l3-8M19 18l-3-8"/></svg>}
export function generateStaticParams(){return Object.keys(regions).map((slug)=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const regionSlug=slug as RegionSlug;const region=regions[regionSlug];if(!region)return{};const seo=getRegionSeo(regionSlug);const indexable=isIndexableRegion(slug);return{title:seo.title,description:seo.description,keywords:seo.keywords,robots:{index:indexable,follow:true},alternates:{canonical:`/busan/${slug}`},openGraph:{title:seo.ogTitle,description:seo.ogDescription,url:`/busan/${slug}`,type:"website",locale:"ko_KR"},twitter:{card:"summary",title:seo.ogTitle,description:seo.ogDescription}};}
export default async function RegionPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const regionSlug=slug as RegionSlug;const region=regions[regionSlug];if(!region)notFound();const detail=getRegionDetail(regionSlug);
const validServices=region.services.map((serviceSlug)=>({serviceSlug,item:services[serviceSlug as ServiceSlug]})).filter((entry)=>Boolean(entry.item));
const universalGuides=universalGuideSlugs.map((guideSlug)=>guides.find((guide)=>guide.slug===guideSlug)).filter((guide):guide is NonNullable<typeof guide>=>Boolean(guide));
const industryGuides=guides.filter((guide)=>isIndexableGuide(guide.slug)).map((guide)=>({guide,score:guide.relatedServices.filter((serviceSlug)=>(region.services as readonly string[]).includes(serviceSlug)).length})).filter(({guide,score})=>score>0&&!universalGuideSlugs.includes(guide.slug as typeof universalGuideSlugs[number])).sort((a,b)=>b.score-a.score).slice(0,2).map(({guide})=>guide);
const relatedGuides=[...universalGuides,...industryGuides].slice(0,6);
const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"부산지역",item:`${baseUrl}/busan`},{"@type":"ListItem",position:3,name:region.name,item:`${baseUrl}/busan/${slug}`}]},{"@context":"https://schema.org","@type":"Service",name:region.primary,description:region.summary,serviceType:"철거·원상복구",areaServed:{"@type":"AdministrativeArea",name:`부산광역시 ${region.name}`},provider:{"@type":"Organization",name:"올바른 철거",url:baseUrl},url:`${baseUrl}/busan/${slug}`},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:detail.faq.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}];
return <main className="page-shell"><style>{`
.detail-tone-blue{--d-bg:#eef4ff;--d-border:#d8e5ff;--d-color:#2458d8}.detail-tone-orange{--d-bg:#fff4e8;--d-border:#f7ddbd;--d-color:#a9570a}.detail-tone-amber{--d-bg:#fff8df;--d-border:#f2e3a8;--d-color:#8b6508}.detail-tone-cyan{--d-bg:#ecf9fb;--d-border:#cfedf1;--d-color:#087b8c}.detail-tone-indigo{--d-bg:#eef0ff;--d-border:#daddff;--d-color:#4c51bf}.detail-tone-green{--d-bg:#edf9f2;--d-border:#d2efde;--d-color:#18794e}.detail-tone-slate{--d-bg:#f1f4f7;--d-border:#dde3ea;--d-color:#475467}.detail-tone-rose{--d-bg:#fff0f3;--d-border:#f5d6df;--d-color:#b4234d}.detail-tone-purple{--d-bg:#f5f0ff;--d-border:#e4d8ff;--d-color:#7048c8}.detail-tone-sky{--d-bg:#edf8ff;--d-border:#d2ecfb;--d-color:#0875a5}
.region-detail-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:var(--d-bg);border:1px solid var(--d-border);color:var(--d-color);transition:.2s ease}.region-detail-icon svg{width:25px;height:25px}.service-card:hover .region-detail-icon{transform:translateY(-2px);background:var(--d-color);color:#fff}.local-point-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:#eef4ff;color:#2458d8;border:1px solid #d8e5ff;margin-bottom:13px}.local-point-icon svg{width:22px;height:22px}.local-check-number{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#edf8ff;color:#0875a5;font-size:11px;font-weight:850}
.haeundae-gallery{margin:28px 0 10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.haeundae-gallery figure{margin:0;border-radius:22px;overflow:hidden;background:#f4f7fb;border:1px solid #e4e9f2;box-shadow:0 12px 30px rgba(22,34,51,.08)}.haeundae-gallery figure:first-child{grid-column:1/-1}.haeundae-gallery img{display:block;width:100%;height:100%;aspect-ratio:16/9;object-fit:cover}.haeundae-gallery figure:first-child img{aspect-ratio:21/9}.haeundae-gallery figcaption{padding:12px 14px;font-size:14px;font-weight:800;color:#243044;background:#fff}@media(max-width:720px){.haeundae-gallery{grid-template-columns:1fr}.haeundae-gallery figure:first-child{grid-column:auto}.haeundae-gallery figure:first-child img,.haeundae-gallery img{aspect-ratio:16/10}}
`}</style>{structuredData.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>)}
<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/busan">부산지역</a><span>›</span><strong>{region.name}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● 부산 지역별 철거</div><h1>{region.primary}<br/><span className="gradient-text">현장 조건 가이드</span></h1><p>{region.summary}</p><div className="hero-points">{region.neighborhoods.map((n)=><span key={n}>{n}</span>)}</div><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a><a className="btn btn-glass" href="/support">폐업지원금 확인</a></div></header>
<HomeEstimateForm region={region.name}/>
{slug==="haeundae"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">HAEUNDAE FIELD TYPES</span><h2>해운대구는 건물 유형별로 철거 범위를 나눠 확인하세요</h2></div><p>아래 이미지는 현장 유형을 이해하기 위한 참고 자료입니다. 실제 시공사례나 해당 동네에서 촬영한 현장사진을 뜻하지 않습니다.</p></div><div className="haeundae-gallery">{haeundaeImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>센텀·우동 업무시설: 관리실 작업승인, 화물승강기 사용시간과 전산배선 철거 주체를 먼저 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>중동 음식점: 내부 후드와 외벽 덕트의 소유·복구 범위를 임대인과 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>좌동·재송동 생활상가: 차량 정차 위치, 보행동선, 공용복도 보양 범위를 현장별로 확인합니다.</span></article></div></section>}
{slug==="gijang"&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">GIJANG SITE TYPES</span><h2>기장군은 상가·산업시설·주택을 구역별로 나눠 확인하세요</h2></div><p>정관·일광의 상가, 장안의 산업시설, 기장읍의 주택·부속시설은 철거 대상과 반출조건이 다릅니다. 다음 항목은 현장별 점검 가이드이며 특정 현장의 시공실적을 의미하지 않습니다.</p></div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>정관·일광 상가: 관리실 공사신고, 공용부 보양, 임차인 설치물과 건물 기본마감의 경계를 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>장안 산업시설·창고: 랙·설비 존치 여부와 전기·배관 차단 담당자, 대형차 회전·상차 공간을 기록합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>기장읍 주택·외곽 현장: 본채·창고·데크·담장 등 부속시설을 구역별로 표시하고 폐기물 운반거리를 확인합니다.</span></article></div><p>상가와 창고, 주택 부속시설이 함께 있는 현장은 전체 면적만 보내기보다 구역별 사진과 철거·존치 대상을 함께 전달하면 견적 범위가 명확해집니다.</p><div className="scenario-grid"><article className="scenario-card"><span>정관·일광 상가</span><h3>임차인 시설과 기본마감이 섞여 있다면</h3><p>임대차 원상복구 기준과 관리실 보양 규정을 확인하고 간판·바닥·급배수의 철거 및 존치 범위를 구역별로 표시합니다.</p></article><article className="scenario-card"><span>장안 창고·산업시설</span><h3>랙과 생산설비를 함께 반출한다면</h3><p>전원·배관 차단 주체와 중량물 해체 순서를 확인하고 차량 회전·상차 공간을 진입로와 별도로 촬영합니다.</p></article><article className="scenario-card"><span>기장읍 주택·부속시설</span><h3>본채와 외부 시설의 범위가 다르다면</h3><p>본채·창고·데크·담장 등 대상별 사진을 구분하고 구조물 해체와 내부 마감 철거를 동일한 작업으로 취급하지 않도록 견적 항목을 나눕니다.</p></article></div><p>위 항목은 기장군 현장 준비를 위한 일반 안내이며 실제 시공사례 또는 확정 견적이 아닙니다.</p></section>}
{slug==="yeongdo"&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">YEONGDO ACCESS CHECK</span><h2>영도구는 철거 면적보다 경사와 계단 반출을 먼저 확인하세요</h2></div><p>영도구의 경사지와 좁은 골목은 차량이 실제로 멈출 수 있는 지점부터 출입구까지의 운반 조건을 확인하는 것이 중요합니다. 아래 내용은 현장 점검 항목이며 특정 현장의 시공실적을 뜻하지 않습니다.</p></div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>청학동 경사지: 상차 가능 지점에서 출입구까지 경사·계단 수·운반거리를 사진과 함께 기록합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>봉래·남항권 창고·작업장: 랙·기계설비의 존치 여부를 표시하고 철재와 일반 폐기물의 반출 순서를 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>동삼동 주거지 인접 현장: 소음작업 시간, 분진차단과 차량 정차 위치를 확인해 보행동선을 확보합니다.</span></article></div><p>견적 요청 시 출입구 사진뿐 아니라 골목 시작점, 경사 구간, 계단과 실제 상차 위치를 함께 전달하면 반출조건을 비교하기 쉽습니다.</p><div className="scenario-grid"><article className="scenario-card"><span>경사지 반출</span><h3>차량이 건물 앞까지 들어오지 못한다면</h3><p>차량 정차 가능 지점과 출입구 사이의 계단 수·경사·운반거리를 따로 기록하고 인력 또는 소형 운반장비 투입 여부를 확인합니다.</p></article><article className="scenario-card"><span>창고·작업장</span><h3>랙과 기계설비가 함께 있다면</h3><p>철거·존치·재사용 항목을 구분하고 설비 전원 차단 담당자, 철재와 일반 폐기물의 분리 반출 순서를 확인합니다.</p></article><article className="scenario-card"><span>인접 주거지</span><h3>주택과 통로를 공유한다면</h3><p>분진차단·보양 범위와 소음작업 시간, 주민 보행동선 및 폐기물 임시 적치 가능 위치를 관리주체와 확인합니다.</p></article></div><p>위 항목은 영도구 현장 준비를 위한 일반 안내이며 실제 시공사례 또는 확정 견적이 아닙니다.</p></section>}
{slug==="dong"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">DONG-GU FIELD TYPES</span><h2>동구는 숙박시설과 노후 상가의 설비 경계를 확인하세요</h2></div><p>초량동 객실·욕실 설비와 범일동 점포의 인접 영업점 보호는 서로 다른 철거 준비 항목입니다. 아래 이미지는 현장 유형을 설명하는 참고 자료이며 해당 동네의 실제 시공사례를 의미하지 않습니다.</p></div><div className="haeundae-gallery">{dongImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>초량동 숙박시설: 객실 가구·욕실 설비와 건물 공용 급배수·전기 라인의 경계를 표시합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>범일동 상가: 인접 점포와 공용통로의 분진차단·보양 범위, 작업시간을 관리주체와 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>수정·좌천동 노후 건물: 기존 배관과 임차인 추가설비를 구분하고 차량 정차·폐기물 상차 위치를 기록합니다.</span></article></div></section>}
{slug==="buk"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">BUK-GU FIELD TYPES</span><h2>북구는 다층 상가와 골목 반출 조건을 따로 확인하세요</h2></div><p>덕천·화명 상권의 승강기·공용부 조건과 구포·만덕 골목의 차량 접근은 견적 준비 항목이 다릅니다. 아래 이미지는 현장 유형을 설명하는 참고 자료이며 해당 동네의 실제 시공사례를 의미하지 않습니다.</p></div><div className="haeundae-gallery">{bukImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>덕천동 다층 상가: 승강기 내부 크기·적재 제한·사용시간과 계단 반출 허용 여부를 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>화명동 주거형 상가: 공용부 보양 범위와 소음작업 가능시간, 급배수 설비의 원상복구 범위를 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>구포·만덕동 골목 현장: 출입구에서 차량 상차 위치까지 실제 운반거리와 임시 적치 가능 여부를 기록합니다.</span></article></div></section>}
{slug==="gangseo"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">GANGSEO FIELD TYPES</span><h2>강서구는 명지 상가와 녹산·신호 산업시설을 구분하세요</h2></div><p>신축 상가의 기본마감 복구와 산업시설의 생산설비 철거는 확인할 항목이 다릅니다. 아래 이미지는 현장 유형 설명을 위한 참고 자료이며 해당 동네의 실제 시공사례를 의미하지 않습니다.</p></div><div className="haeundae-gallery">{gangseoImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>명지동 신축 상가: 관리실 보양 규정과 기본마감, 임차인 설치물의 원상복구 범위를 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>녹산·신호동 산업시설: 설비별 전기·가스·배관 차단 담당자와 존치 설비, 장비 투입공간을 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>대저동 등 접근조건이 다른 현장: 출입문 폭, 대형차 회전·정차 위치와 폐기물 임시 적치공간을 기록합니다.</span></article></div></section>}
{slug==="saha"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">SAHA FIELD TYPES</span><h2>사하구는 하단 상권과 장림 산업시설을 나눠 준비하세요</h2></div><p>음식점·학원의 내부 마감 철거와 공장 생산설비 철거는 작업범위와 차단 절차가 다릅니다. 아래 이미지는 현장 유형 설명을 위한 참고 자료로, 해당 동네의 실제 시공사례를 의미하지 않습니다.</p></div><div className="haeundae-gallery">{sahaImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>하단동 음식점·학원: 주방 덕트와 급배수, 칸막이·배선의 철거 및 존치 범위를 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>장림동 공장·작업장: 생산설비와 내장재를 분리해 견적하고, 전기·배관 차단 담당자와 반출 장비를 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>괴정·다대동 골목 현장: 출입구부터 폐기물 상차 위치까지 실제 운반거리와 차량 정차 가능 여부를 기록합니다.</span></article></div></section>}
{slug==="nam"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">NAM-GU FIELD TYPES</span><h2>남구는 업무시설·상가·주거지 현장을 구분해 확인하세요</h2></div><p>문현동의 업무·상가 복합건물과 대연·용호·용당의 점포 및 주거지 인접 현장은 관리규정과 반출조건이 다를 수 있습니다. 아래 이미지는 현장 유형을 설명하는 참고 자료이며 실제 해당 동네 시공사례를 의미하지 않습니다.</p></div><div className="haeundae-gallery">{namImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.caption}</figcaption></figure>)}</div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>문현동 복합건물: 관리실 공사신고와 승강기 예약, 전기·통신 설비의 유지 범위를 확인합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>대연동 점포: 바닥 철거 깊이와 간판 타공부 마감, 임대인 원상복구 요구사항을 구분합니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>용호·용당동 현장: 진입로 폭, 차량 정차 가능 위치와 인력 운반거리를 사진으로 남깁니다.</span></article></div></section>}
{slug==="busanjin"&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">SEOMYEON · JEONPO CHECK</span><h2>부산진구 소형 점포는 철거 면적보다 반출 조건을 먼저 확인하세요</h2></div><p>서면·전포의 상가 철거와 당감·범천의 주거지 인접 점포는 같은 면적이어도 출입구, 적치공간, 작업시간에 따라 준비 항목이 달라집니다.</p></div><div className="scenario-grid"><article className="scenario-card"><span>서면·부전동</span><h3>영업 중인 상가 통로를 함께 사용한다면</h3><p>공용복도 폭과 승강기 예약시간을 확인하고, 폐기물 포장·이동 시간을 소음이 큰 해체 공정과 구분합니다.</p></article><article className="scenario-card"><span>전포동</span><h3>카페의 외부 간판과 내부 설비를 함께 철거한다면</h3><p>카운터·급배수·전기와 외벽 사인물의 철거 주체를 나누고, 타공부 마감은 임대인과 서면으로 범위를 확인합니다.</p></article><article className="scenario-card"><span>당감·범천동</span><h3>주거지와 가까운 골목 점포라면</h3><p>차량 정차 위치와 소형 운반거리를 기록하고, 건물 규정과 인접 주거공간을 고려해 작업시간을 조율합니다.</p></article></div><div className="detail-list-grid"><article className="detail-list-card"><b className="local-check-number">01</b><span>견적 범위: 천장·바닥·칸막이·주방설비를 각각 철거 또는 존치 항목으로 구분하고, 간판과 타공부 마감은 별도 표시합니다.</span></article><article className="detail-list-card"><b className="local-check-number">02</b><span>현장 사진: 점포 전체, 출입문과 공용통로, 간판, 차량 상차 위치를 함께 촬영하면 반출 조건을 설명하기 쉽습니다.</span></article><article className="detail-list-card"><b className="local-check-number">03</b><span>일정 확인: 임대차 종료일, 관리실 공사신고, 승강기 사용 가능시간과 인접 점포 영업시간을 따로 확인합니다.</span></article></div><p>이 내용은 지역별 현장 준비를 위한 일반 안내이며, 실제 건물 규정과 현장 상태는 상담 전에 별도 확인해야 합니다. 실제 부산진구 시공사례로 확인되지 않은 이미지는 게시하지 않았습니다.</p></section>}
{slug==="dongnae"&&<section className="section"><div className="section-heading"><div><span className="section-kicker">DONGNAE DEMOLITION</span><h2>동래구 철거 서비스 이미지</h2></div><p>동래구 상가·학원·병원·사무실·인테리어 철거 유형을 이미지로 확인할 수 있습니다.</p></div><div className="haeundae-gallery">{dongnaeImages.map((image)=><figure key={image.src}><img src={image.src} alt={image.alt} loading="lazy"/><figcaption>{image.alt}</figcaption></figure>)}</div></section>}
<section className="split"><article className="info-card"><span className="section-kicker">LOCAL FOCUS</span><h2>{region.name}에서 먼저 볼 기준</h2><p>{detail.focus}</p></article><article className="info-card"><span className="section-kicker">BUILDING RULE</span><h2>건물 규정과 반출조건 확인</h2><p>{detail.buildingRule??"작업 가능 시간, 공용부 보양, 승강기 사용조건, 차량 진입과 폐기물 상차 위치는 현장마다 달라질 수 있습니다."}</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL POINTS</span><h2>{region.name} 철거에서 중요한 점</h2></div><p>지역명을 반복하기보다 실제 작업에 영향을 주는 현장 요소를 정리했습니다.</p></div><div className="feature-grid">{region.points.map((point,i)=><article className="feature-card" key={point}><div className="local-point-icon"><PointIcon index={i}/></div><p>{point}</p></article>)}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">FIELD CHECKLIST</span><h2>{region.name} 현장에서 확인할 항목</h2></div><p>견적 전 사진과 현장 확인에서 이 항목을 먼저 보면 반출·보양·설비 조건을 구체적으로 정리하기 쉽습니다.</p></div><div className="detail-list-grid">{detail.fieldChecks.map((text,i)=><article className="detail-list-card" key={text}><b className="local-check-number">{String(i+1).padStart(2,"0")}</b><span>{text}</span></article>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL SCENARIOS</span><h2>{region.name}에서 이런 현장이라면?</h2></div><p>지역별 건물과 도로 조건이 철거 방식에 어떤 영향을 줄 수 있는지 상황별로 정리했습니다.</p></div><div className="scenario-grid">{detail.scenarios.map((entry)=><article className="scenario-card" key={entry.title}><span>현장 변수</span><h3>{entry.title}</h3><p>{entry.text}</p></article>)}</div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">NEIGHBORHOOD CHECK</span><h2>{region.neighborhoods.slice(0,3).join(" · ")} 등 현장별 확인사항</h2></div><p>{detail.neighborhoodNote??`같은 ${region.name} 안에서도 건물 연식, 도로 폭, 주차와 승강기 조건은 현장마다 다르므로 실제 반출 조건을 함께 확인하는 것이 좋습니다.`}</p></div><div className="link-cloud" aria-label={`${region.name} 주요 동네`}>{region.neighborhoods.map((name)=><span className="info-chip" key={name}>{name} 현장</span>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">LOCAL SERVICES</span><h2>{region.name}에서 많이 확인하는 철거 유형</h2></div><p>지역 조건과 함께 업종별 설비·원상복구 범위를 확인하세요.</p></div><div className="service-grid">{validServices.map(({serviceSlug,item})=>{const tone=serviceTone[serviceSlug]??"blue";return <a className={`service-card detail-tone-${tone}`} href={`/service/${serviceSlug}`} key={serviceSlug}><div className="service-card-top"><span className="region-detail-icon"><CardIcon type={serviceSlug}/></span><span className="service-card-arrow">↗</span></div><strong>{item.name}</strong><span>{item.summary}</span></a>})}</div></section>
{relatedGuides.length>0&&<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">PREPARE BY INTENT</span><h2>{region.name} 철거 전에 순서대로 확인하세요</h2></div><p>지역별 업종 정보와 함께 견적 비교 → 원상복구 범위 → 폐기물 기준을 먼저 확인하고, 이 지역의 실제 업종과 연결되는 검토 완료 가이드를 이어서 볼 수 있습니다.</p></div><div className="service-grid">{relatedGuides.map((guide,i)=>{const tones=["blue","purple","orange","green","cyan","indigo"];const tone=tones[i%tones.length];return <a className={`service-card detail-tone-${tone}`} href={`/guide/${guide.slug}`} key={guide.slug}><div className="service-card-top"><span className="region-detail-icon"><GuideIcon slug={guide.slug}/></span><span className="service-card-arrow">↗</span></div><strong>{guide.title}</strong><span>{guide.description}</span></a>})}</div></section>}
<section className="section faq"><div className="section-heading"><div><span className="section-kicker">FAQ</span><h2>{region.name} 철거 자주 묻는 질문</h2></div><p>지역별 현장 상담 전에 자주 확인하는 내용을 정리했습니다.</p></div>{detail.faq.map((faq)=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>
<section className="final-cta"><div><span className="section-kicker">LOCAL ESTIMATE</span><h2>{region.name} 현장 조건을 확인했다면<br/>실제 철거범위를 상담하세요</h2><p>현장사진과 기본정보를 준비하면 작업범위와 원상복구 항목을 더 구체적으로 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">준비정보 6가지</a></div></section></main>;}
