import { notFound } from "next/navigation";
import { guides as coreGuides, guideBySlug } from "@/data/guides";
import { guides as allGuides } from "@/data/allGuides";
import { services, type ServiceSlug } from "@/data/services";
import { regions } from "@/data/regions";
import { getGuideDetail } from "@/data/guideDetails";
import { guideDetailsExtra } from "@/data/guideDetailsExtra";
import { getGuideFaq } from "@/data/guideFaq";
import ClosureSupport from "@/components/ClosureSupport";
const baseUrl="https://www.parcelout.kr";const inquiryUrl="https://maxpool.olbarun.kr/";
export function generateStaticParams(){return coreGuides.map((guide)=>({slug:guide.slug}));}
function buildGuideSocialMeta(slug:string,category:string,title:string,description:string){
  if(category.includes("지원"))return{ogTitle:`폐업 전 먼저 확인 | ${title}`,ogDescription:`지원 신청과 철거 순서를 함께 확인할 수 있도록 ${description}`,twitter:`폐업지원과 철거 준비를 한 번에 확인하세요.`};
  if(category.includes("비용")||slug.includes("estimate"))return{ogTitle:`철거 견적을 비교하기 전에 | ${title}`,ogDescription:`가격 숫자보다 먼저 봐야 할 범위·반출·설비 조건을 중심으로 ${description}`,twitter:`철거 견적 비교 전에 확인할 실무 기준입니다.`};
  if(category.includes("원상복구")||slug.includes("restoration"))return{ogTitle:`원상복구 범위를 정할 때 | ${title}`,ogDescription:`임대인 협의와 철거범위를 나누는 기준을 중심으로 ${description}`,twitter:`원상복구 범위와 철거 항목을 구분해 확인하세요.`};
  if(category.includes("산업"))return{ogTitle:`공장·창고 철거 실무 | ${title}`,ogDescription:`설비·전력·배관·반출조건처럼 산업시설에서 중요한 요소를 중심으로 ${description}`,twitter:`산업시설 철거 전 설비와 반출조건을 확인하세요.`};
  if(category.includes("주거"))return{ogTitle:`주거 철거 체크 | ${title}`,ogDescription:`관리규정·보양·욕실·주방 등 주거공간 철거의 실제 확인사항을 중심으로 ${description}`,twitter:`아파트·주거 철거 전에 확인할 핵심 항목입니다.`};
  if(category.includes("업종"))return{ogTitle:`업종별 폐업철거 가이드 | ${title}`,ogDescription:`업종 전용 설비와 원상복구 범위를 구분해 볼 수 있도록 ${description}`,twitter:`업종마다 다른 설비와 철거범위를 확인하세요.`};
  return{ogTitle:`철거 준비 실무 가이드 | ${title}`,ogDescription:`현장 확인과 작업범위를 정하는 데 필요한 기준을 중심으로 ${description}`,twitter:`철거 전 놓치기 쉬운 준비사항을 확인하세요.`};
}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guideBySlug(slug);if(!guide)return{};const social=buildGuideSocialMeta(slug,guide.category,guide.title,guide.description);return{title:guide.title,description:guide.description,keywords:guide.keywords,robots:{index:true,follow:true},alternates:{canonical:`/guide/${slug}`},openGraph:{title:social.ogTitle,description:social.ogDescription,url:`/guide/${slug}`,type:"article"},twitter:{card:"summary",title:social.ogTitle,description:social.twitter}};}
const tones=["blue","orange","green","purple","cyan","rose","amber","indigo"];
function Icon({type}:{type:string}){const p={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(type==="cost")return <svg {...p}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2M8 18h8"/></svg>;if(type==="restore")return <svg {...p}><path d="M3 11l9-7 9 7M5 10v10h14V10M9 20v-6h6v6"/><path d="M17 5v4"/></svg>;if(type==="document")return <svg {...p}><path d="M6 3h9l4 4v14H6zM15 3v5h4M9 12h6M9 16h6"/></svg>;if(type==="utility")return <svg {...p}><path d="M13 2L6 13h6l-1 9 7-12h-6z"/></svg>;if(type==="building")return <svg {...p}><path d="M4 21V7h7v14M13 21V3h7v18M3 21h18"/><path d="M7 10h1M7 14h1M16 7h1M16 11h1M16 15h1"/></svg>;if(type==="warning")return <svg {...p}><path d="M12 3l9 17H3zM12 9v5M12 17h.01"/></svg>;if(type==="camera")return <svg {...p}><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M8 6l1-2h6l1 2"/><circle cx="12" cy="13" r="3"/></svg>;if(type==="location")return <svg {...p}><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11z"/><circle cx="12" cy="10" r="2"/></svg>;if(type==="tool")return <svg {...p}><path d="M14 6l4-4 4 4-4 4M17 7L8 16M6 14l4 4-3 3-4-4z"/></svg>;if(type==="flow")return <svg {...p}><circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 6h7a3 3 0 0 1 3 3v1M17 14v1a3 3 0 0 1-3 3H7M10 15l-3 3 3 3"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="9"/><path d="M8 12l2.5 2.5L16 9"/></svg>}
function guideIcon(slug:string,category:string){if(slug.includes("cost")||slug.includes("estimate"))return"cost";if(slug.includes("restoration"))return"restore";if(slug.includes("utility"))return"utility";if(slug.includes("management"))return"building";if(slug.includes("support")||category.includes("지원"))return"document";return"tool"}
function serviceTone(slug:string){if(["restaurant","cafe","bakery","pub"].includes(slug))return"orange";if(["hospital","dental","pharmacy"].includes(slug))return"green";if(["factory","warehouse","mart"].includes(slug))return"indigo";if(["beauty-salon","beauty-shop","pet-shop"].includes(slug))return"rose";if(["academy","study-cafe"].includes(slug))return"purple";return"blue"}
export default async function GuideDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guideBySlug(slug);if(!guide)notFound();const detail=getGuideDetail(slug)??guideDetailsExtra[slug];const faqItems=getGuideFaq(slug);const estimateGuideHref=slug==="demolition-estimate-checklist"?"/guide/restoration-scope-checklist":"/guide/demolition-estimate-checklist";const estimateGuideLabel=slug==="demolition-estimate-checklist"?"원상복구 범위 체크리스트":"견적 비교 체크리스트";const validServices=guide.relatedServices.map((serviceSlug)=>({serviceSlug,item:services[serviceSlug as ServiceSlug]})).filter((entry)=>Boolean(entry.item));const relatedRegions=Object.entries(regions).map(([regionSlug,region])=>({regionSlug,region,score:region.services.filter((serviceSlug)=>guide.relatedServices.includes(serviceSlug as never)).length})).filter(({score})=>score>0).sort((a,b)=>b.score-a.score).slice(0,6);const relatedGuides=allGuides.filter((candidate)=>candidate.slug!==guide.slug).map((candidate)=>({candidate,serviceScore:candidate.relatedServices.filter((s)=>guide.relatedServices.includes(s)).length,categoryScore:candidate.category===guide.category?1:0,keywordScore:candidate.keywords.filter((k)=>guide.keywords.includes(k)).length})).filter(({serviceScore,categoryScore,keywordScore})=>serviceScore>0||categoryScore>0||keywordScore>0).sort((a,b)=>(b.serviceScore*3+b.categoryScore*2+b.keywordScore)-(a.serviceScore*3+a.categoryScore*2+a.keywordScore)).slice(0,5).map(({candidate})=>candidate);const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"철거가이드",item:`${baseUrl}/guide`},{"@type":"ListItem",position:3,name:guide.title,item:`${baseUrl}/guide/${slug}`}]},{"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,mainEntityOfPage:`${baseUrl}/guide/${slug}`,author:{"@type":"Organization",name:"올바른철거",url:baseUrl},publisher:{"@type":"Organization",name:"올바른철거",url:baseUrl},about:guide.keywords},...(faqItems.length?[{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqItems.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}]:[])];return <main className="page-shell">
<style>{`.tone-blue{--i-bg:#eef4ff;--i-border:#d8e5ff;--i-color:#2458d8}.tone-orange{--i-bg:#fff4e8;--i-border:#f7ddbd;--i-color:#a9570a}.tone-green{--i-bg:#edf9f2;--i-border:#d2efde;--i-color:#18794e}.tone-purple{--i-bg:#f5f0ff;--i-border:#e4d8ff;--i-color:#7048c8}.tone-cyan{--i-bg:#ecf9fb;--i-border:#cfedf1;--i-color:#087b8c}.tone-rose{--i-bg:#fff0f3;--i-border:#f5d6df;--i-color:#b4234d}.tone-amber{--i-bg:#fff8df;--i-border:#f2e3a8;--i-color:#8b6508}.tone-indigo{--i-bg:#eef0ff;--i-border:#daddff;--i-color:#4c51bf}.guide-icon{width:50px;height:50px;border-radius:15px;display:grid;place-items:center;background:var(--i-bg);border:1px solid var(--i-border);color:var(--i-color);margin-bottom:14px;transition:.2s ease}.guide-icon svg{width:25px;height:25px}.feature-card:hover .guide-icon,.service-card:hover .guide-icon{background:var(--i-color);color:#fff;transform:translateY(-2px) scale(1.04);box-shadow:0 8px 18px rgba(17,24,39,.1)}.mini-icon{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--i-bg);border:1px solid var(--i-border);color:var(--i-color);flex:0 0 auto}.mini-icon svg{width:18px;height:18px}.guide-list-card{display:flex;gap:12px;align-items:flex-start}.flow-icon{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;background:var(--i-bg);border:1px solid var(--i-border);color:var(--i-color);margin-bottom:10px}.flow-icon svg{width:20px;height:20px}`} </style>
{structuredData.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>)}<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/guide">철거가이드</a><span>›</span><strong>{guide.category}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● {guide.category}</div><h1>{guide.title}</h1><p>{guide.description}</p><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지</a><a className="btn btn-glass" href="/support">폐업지원금 확인</a></div></header>
<section className="split"><article className="info-card"><span className="section-kicker">HOW TO USE</span><h2>이 글에서 확인할 내용</h2><p>철거·폐업 과정에서 먼저 결정해야 할 항목을 순서대로 확인할 수 있도록 핵심 기준을 나눠 정리했습니다.</p></article><article className="info-card"><span className="section-kicker">FIELD NOTE</span><h2>현장마다 조건은 다릅니다</h2><p>계약조건, 설비, 마감재와 반출환경에 따라 실제 공사 범위와 비용은 달라질 수 있으므로 최종 판단 전 현장 확인이 필요합니다.</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">KEY GUIDE</span><h2>핵심 내용</h2></div><p>먼저 판단해야 할 기준을 4개 항목으로 정리했습니다.</p></div><div className="feature-grid">{guide.sections.map((s,i)=>{const tone=tones[i%tones.length];return <article className={`feature-card tone-${tone}`} key={s.title}><div className="guide-icon"><Icon type={["document","tool","warning","flow"][i%4]}/></div><h3>{s.title}</h3><p>{s.body}</p></article>})}</div></section>
{detail&&<><section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">FIELD CHECKLIST</span><h2>공사 전에 직접 확인할 체크리스트</h2></div><p>견적을 받기 전에 아래 항목을 사진과 함께 정리하면 작업범위를 설명하기 쉬워집니다.</p></div><div className="detail-list-grid">{detail.checklist.map((text,i)=>{const tone=tones[i%tones.length];return <article className={`detail-list-card guide-list-card tone-${tone}`} key={text}><span className="mini-icon"><Icon type="check"/></span><span>{text}</span></article>})}</div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">COMMON MISTAKES</span><h2>이 주제에서 자주 놓치는 부분</h2></div><p>철거 후 다시 공사하거나 범위를 재협의하는 일을 줄이려면 공사 전에 확인하세요.</p></div><div className="scenario-grid">{detail.mistakes.map((m,i)=><article className={`scenario-card tone-${tones[(i+5)%tones.length]}`} key={m.title}><span className="mini-icon"><Icon type="warning"/></span><h3>{m.title}</h3><p>{m.text}</p></article>)}</div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">WORK FLOW</span><h2>실제 준비 순서</h2></div><p>현장 조건에 따라 달라질 수 있지만, 무엇을 먼저 확인해야 하는지 흐름을 잡는 데 사용할 수 있습니다.</p></div><div className="process-grid">{detail.timeline.map((step,i)=><article className={`process-step tone-${tones[(i+2)%tones.length]}`} key={step.title}><span className="flow-icon"><Icon type="flow"/></span><b>{step.label}</b><strong>{step.title}</strong><p>{step.text}</p></article>)}</div></section><section className="section split"><article className="info-card"><span className="section-kicker">ASK BEFORE QUOTE</span><h2>견적 전에 물어볼 질문</h2><ul>{detail.questions.map((q)=><li key={q}>{q}</li>)}</ul></article><article className="info-card"><span className="section-kicker">PHOTO TIP</span><h2>사진은 이렇게 준비하세요</h2><p>현장 전체가 보이는 사진부터 주요 설비·마감재, 출입구, 계단·승강기, 차량 상차 위치 순서로 찍으면 면적만 전달하는 것보다 현장조건을 파악하기 쉽습니다.</p><p>철거하지 않고 남길 시설도 따로 찍어두면 보존 범위를 설명하는 데 도움이 됩니다.</p></article></section></>}
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">READY FOR ESTIMATE</span><h2>가이드를 확인했다면 이 6가지를 준비하세요</h2></div><p>현장 위치, 업종·면적, 층수·엘리베이터, 철거범위, 희망일정과 현장사진을 정리하면 실제 현장에 적용되는 범위를 더 빠르게 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-primary" href={inquiryUrl}>무료견적 문의하기</a><a className="btn btn-glass" href="/estimate">견적 준비정보 6가지 확인</a><a className="btn btn-glass" href={estimateGuideHref}>{estimateGuideLabel}</a></div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">VISUAL GUIDE</span><h2>가이드 이미지 영역</h2></div><p>실제 현장사진과 체크리스트 이미지가 확보되면 주제에 맞게 교체합니다.</p></div><div className="image-grid">{[1,2,3,4].map((n)=><figure className="image-slot" key={n}><div className="placeholder"><strong>가이드 이미지 {n}</strong><span>/public/images/guides/{guide.slug}/{String(n).padStart(2,"0")}.webp</span></div></figure>)}</div></section><ClosureSupport serviceName={guide.category}/>
{validServices.length>0&&<section className="section"><div className="section-heading"><div><span className="section-kicker">RELATED SERVICE</span><h2>가이드와 연결되는 업종별 철거</h2></div><p>일반적인 체크사항을 실제 업종의 설비·원상복구 조건과 연결해서 확인하세요.</p></div><div className="service-grid">{validServices.map(({serviceSlug,item})=>{const tone=serviceTone(serviceSlug);return <a className={`service-card tone-${tone}`} href={`/service/${serviceSlug}`} key={serviceSlug}><div className="service-card-top"><span className="guide-icon"><Icon type="tool"/></span><span className="service-card-arrow">↗</span></div><strong>{item.name}</strong><span>{item.summary}</span></a>})}</div></section>}
{relatedGuides.length>0&&<section className="section"><div className="section-heading"><div><span className="section-kicker">NEXT READING</span><h2>이어서 확인할 철거 가이드</h2></div><p>현재 글과 업종·검색의도가 연결되는 기존·신규 가이드를 함께 추천합니다.</p></div><div className="service-grid">{relatedGuides.map((r,i)=>{const tone=tones[i%tones.length];return <a className={`service-card tone-${tone}`} href={`/guide/${r.slug}`} key={r.slug}><div className="service-card-top"><span className="guide-icon"><Icon type={guideIcon(r.slug,r.category)}/></span><span className="service-card-arrow">↗</span></div><strong>{r.title}</strong><span>{r.description}</span></a>})}</div></section>}
{faqItems.length>0&&<section className="section faq"><div className="section-heading"><div><span className="section-kicker">FAQ</span><h2>자주 묻는 질문</h2></div><p>이 가이드 주제에서 실제 상담 전에 많이 확인하는 항목을 정리했습니다.</p></div>{faqItems.map((faq)=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>}
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">LOCAL GUIDE</span><h2>부산 지역별 현장 조건도 함께 확인하세요</h2></div><p>같은 업종이라도 층수, 골목 진입, 주차, 엘리베이터와 관리규정에 따라 작업 방식이 달라질 수 있습니다.</p></div>{relatedRegions.length>0&&<div className="service-grid">{relatedRegions.map(({regionSlug,region},i)=>{const tone=tones[(i+4)%tones.length];return <a className={`service-card tone-${tone}`} href={`/busan/${regionSlug}`} key={regionSlug}><div className="service-card-top"><span className="guide-icon"><Icon type="location"/></span><span className="service-card-arrow">↗</span></div><strong>{region.name} 철거</strong><span>{region.neighborhoods.slice(0,3).join(" · ")} 등 지역별 반출·건물 조건 확인</span></a>})}</div>}<div className="cta-row"><a className="btn btn-glass" href="/busan">부산 16개 구·군 전체 보기</a><a className="btn btn-glass" href="/service">전체 철거서비스 보기</a><a className="btn btn-glass" href="/guide">전체 가이드 보기</a></div></section>
<section className="final-cta"><div><span className="section-kicker">FIELD CHECK</span><h2>가이드에서 기준을 확인했다면<br/>내 현장 조건을 정리하세요</h2><p>현장 위치, 업종·면적, 층수·엘리베이터, 철거범위, 희망일정과 현장사진을 준비하면 실제 철거범위와 원상복구 항목을 더 구체적으로 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/estimate">준비정보 6가지</a></div></section></main>;
}