import { notFound } from "next/navigation";
import { guides, guideBySlug } from "@/data/guides";
import { services, type ServiceSlug } from "@/data/services";
import { regions } from "@/data/regions";
import { getGuideDetail } from "@/data/guideDetails";
import { guideDetailsExtra } from "@/data/guideDetailsExtra";
import { getGuideFaq } from "@/data/guideFaq";
import ClosureSupport from "@/components/ClosureSupport";
const baseUrl="https://busanall.vercel.app";
export function generateStaticParams(){return guides.map((guide)=>({slug:guide.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guideBySlug(slug);if(!guide)return{};return{title:guide.title,description:guide.description,keywords:guide.keywords,alternates:{canonical:`/guide/${slug}`},openGraph:{title:guide.title,description:guide.description,url:`/guide/${slug}`,type:"article"}};}
export default async function GuideDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guideBySlug(slug);if(!guide)notFound();const detail=getGuideDetail(slug)??guideDetailsExtra[slug];const faqItems=getGuideFaq(slug);const validServices=guide.relatedServices.map((serviceSlug)=>({serviceSlug,item:services[serviceSlug as ServiceSlug]})).filter((entry)=>Boolean(entry.item));const relatedRegions=Object.entries(regions).map(([regionSlug,region])=>({regionSlug,region,score:region.services.filter((serviceSlug)=>guide.relatedServices.includes(serviceSlug as never)).length})).filter(({score})=>score>0).sort((a,b)=>b.score-a.score).slice(0,6);const relatedGuides=guides.filter((candidate)=>candidate.slug!==guide.slug).map((candidate)=>({candidate,serviceScore:candidate.relatedServices.filter((s)=>guide.relatedServices.includes(s)).length,categoryScore:candidate.category===guide.category?1:0,keywordScore:candidate.keywords.filter((k)=>guide.keywords.includes(k)).length})).filter(({serviceScore,categoryScore,keywordScore})=>serviceScore>0||categoryScore>0||keywordScore>0).sort((a,b)=>(b.serviceScore*3+b.categoryScore*2+b.keywordScore)-(a.serviceScore*3+a.categoryScore*2+a.keywordScore)).slice(0,4).map(({candidate})=>candidate);const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:baseUrl},{"@type":"ListItem",position:2,name:"철거가이드",item:`${baseUrl}/guide`},{"@type":"ListItem",position:3,name:guide.title,item:`${baseUrl}/guide/${slug}`}]},{"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,mainEntityOfPage:`${baseUrl}/guide/${slug}`,author:{"@type":"Organization",name:"올바른철거",url:baseUrl},publisher:{"@type":"Organization",name:"올바른철거",url:baseUrl},about:guide.keywords},...(faqItems.length?[{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqItems.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))}]:[])];return <main className="page-shell">
{structuredData.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>)}
<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><a href="/guide">철거가이드</a><span>›</span><strong>{guide.category}</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">● {guide.category}</div><h1>{guide.title}</h1><p>{guide.description}</p><div className="cta-row"><a className="btn btn-primary" href="/estimate">무료 현장견적</a><a className="btn btn-glass" href="/support">폐업지원금 확인</a></div></header>
<section className="split"><article className="info-card"><span className="section-kicker">HOW TO USE</span><h2>이 글에서 확인할 내용</h2><p>철거·폐업 과정에서 먼저 결정해야 할 항목을 순서대로 확인할 수 있도록 핵심 기준을 나눠 정리했습니다.</p></article><article className="info-card"><span className="section-kicker">FIELD NOTE</span><h2>현장마다 조건은 다릅니다</h2><p>계약조건, 설비, 마감재와 반출환경에 따라 실제 공사 범위와 비용은 달라질 수 있으므로 최종 판단 전 현장 확인이 필요합니다.</p></article></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">KEY GUIDE</span><h2>핵심 내용</h2></div><p>먼저 판단해야 할 기준을 4개 항목으로 정리했습니다.</p></div><div className="feature-grid">{guide.sections.map((s,i)=><article className="feature-card" key={s.title}><div className="feature-no">0{i+1}</div><h2>{s.title}</h2><p>{s.body}</p></article>)}</div></section>
{detail&&<><section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">FIELD CHECKLIST</span><h2>공사 전에 직접 확인할 체크리스트</h2></div><p>견적을 받기 전에 아래 항목을 사진과 함께 정리하면 작업범위를 설명하기 쉬워집니다.</p></div><div className="detail-list-grid">{detail.checklist.map((text,i)=><article className="detail-list-card" key={text}><b>{String(i+1).padStart(2,"0")}</b><span>{text}</span></article>)}</div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">COMMON MISTAKES</span><h2>이 주제에서 자주 놓치는 부분</h2></div><p>철거 후 다시 공사하거나 범위를 재협의하는 일을 줄이려면 공사 전에 확인하세요.</p></div><div className="scenario-grid">{detail.mistakes.map((m)=><article className="scenario-card" key={m.title}><span>주의사항</span><h3>{m.title}</h3><p>{m.text}</p></article>)}</div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">WORK FLOW</span><h2>실제 준비 순서</h2></div><p>현장 조건에 따라 달라질 수 있지만, 무엇을 먼저 확인해야 하는지 흐름을 잡는 데 사용할 수 있습니다.</p></div><div className="process-grid">{detail.timeline.map((step)=><article className="process-step" key={step.title}><b>{step.label}</b><strong>{step.title}</strong><p>{step.text}</p></article>)}</div></section><section className="section split"><article className="info-card"><span className="section-kicker">ASK BEFORE QUOTE</span><h2>견적 전에 물어볼 질문</h2><ul>{detail.questions.map((q)=><li key={q}>{q}</li>)}</ul></article><article className="info-card"><span className="section-kicker">PHOTO TIP</span><h2>사진은 이렇게 준비하세요</h2><p>현장 전체가 보이는 사진부터 주요 설비·마감재, 출입구, 계단·승강기, 차량 상차 위치 순서로 찍으면 면적만 전달하는 것보다 현장조건을 파악하기 쉽습니다.</p><p>철거하지 않고 남길 시설도 따로 찍어두면 보존 범위를 설명하는 데 도움이 됩니다.</p></article></section></>}
<section className="section"><div className="section-heading"><div><span className="section-kicker">VISUAL GUIDE</span><h2>가이드 이미지 영역</h2></div><p>실제 현장사진과 체크리스트 이미지가 확보되면 주제에 맞게 교체합니다.</p></div><div className="image-grid">{[1,2,3,4].map((n)=><figure className="image-slot" key={n}><div className="placeholder"><strong>가이드 이미지 {n}</strong><span>/public/images/guides/{guide.slug}/{String(n).padStart(2,"0")}.webp</span></div></figure>)}</div></section>
<ClosureSupport serviceName={guide.category}/>
{validServices.length>0&&<section className="section"><div className="section-heading"><div><span className="section-kicker">RELATED SERVICE</span><h2>가이드와 연결되는 업종별 철거</h2></div><p>일반적인 체크사항을 실제 업종의 설비·원상복구 조건과 연결해서 확인하세요.</p></div><div className="service-grid">{validServices.map(({serviceSlug,item})=><a className="service-card" href={`/service/${serviceSlug}`} key={serviceSlug}><div className="service-card-top"><span className="service-card-icon">{item.name.slice(0,1)}</span><span className="service-card-arrow">↗</span></div><strong>{item.name}</strong><span>{item.summary}</span></a>)}</div></section>}
{relatedGuides.length>0&&<section className="section"><div className="section-heading"><div><span className="section-kicker">NEXT READING</span><h2>이어서 확인할 철거 가이드</h2></div><p>현재 글과 업종·주제가 겹치는 글을 연결했습니다.</p></div><div className="service-grid">{relatedGuides.map((r)=><a className="service-card" href={`/guide/${r.slug}`} key={r.slug}><div className="service-card-top"><span className="service-card-icon">G</span><span className="service-card-arrow">↗</span></div><strong>{r.title}</strong><span>{r.description}</span></a>)}</div></section>}
{faqItems.length>0&&<section className="section faq"><div className="section-heading"><div><span className="section-kicker">FAQ</span><h2>자주 묻는 질문</h2></div><p>이 가이드 주제에서 실제 상담 전에 많이 확인하는 항목을 정리했습니다.</p></div>{faqItems.map((faq)=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>}
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">LOCAL GUIDE</span><h2>부산 지역별 현장 조건도 함께 확인하세요</h2></div><p>같은 업종이라도 층수, 골목 진입, 주차, 엘리베이터와 관리규정에 따라 작업 방식이 달라질 수 있습니다.</p></div>{relatedRegions.length>0&&<div className="service-grid">{relatedRegions.map(({regionSlug,region})=><a className="service-card" href={`/busan/${regionSlug}`} key={regionSlug}><div className="service-card-top"><span className="service-card-icon">{region.name.slice(0,1)}</span><span className="service-card-arrow">↗</span></div><strong>{region.name} 철거</strong><span>{region.neighborhoods.slice(0,3).join(" · ")} 등 지역별 반출·건물 조건 확인</span></a>)}</div>}<div className="cta-row"><a className="btn btn-glass" href="/busan">부산 16개 구·군 전체 보기</a><a className="btn btn-glass" href="/service">전체 철거서비스 보기</a><a className="btn btn-glass" href="/guide">전체 가이드 보기</a></div></section>
<section className="final-cta"><div><span className="section-kicker">FIELD CHECK</span><h2>내 현장에 적용되는 범위는<br/>현장에서 확인하세요</h2><p>임대차 조건과 설비, 폐기물 반출조건을 함께 확인해야 실제 철거범위와 견적을 구체화할 수 있습니다.</p></div><a className="btn btn-light" href="/estimate">무료 현장견적</a></section></main>;
}
