const inquiryUrl = "https://maxpool.olbarun.kr/";
const officialNotice = "https://www.sbiz24.kr/";
const hopeUrl = "https://hope.sbiz.or.kr/";
const busan2026 = "https://www.busan.go.kr/nhot/1718623";
const busanEmployment = "https://www.busan.go.kr/nbtnewsBU/1726917";
const bukguReference = "https://www.bsbukgu.go.kr/board/view.bsbukgu?boardId=BBS_0000023&menuCd=DOM_000000105001001000&dataSid=1106060";
export const metadata = {title:"2026 부산 폐업지원금·점포철거비 | 대상·제외조건·신청",description:"2026 부산 폐업 소상공인이 확인할 희망리턴패키지 점포철거비 최대 600만원, 3.3㎡당 20만원 기준과 지원 제외 사례, 증빙서류, 부산 재취업 지원을 정리합니다.",keywords:["2026 폐업지원금","부산 폐업지원금","부산 점포철거비 지원","희망리턴패키지 철거비","폐업철거 지원금"],alternates:{canonical:"/support"},openGraph:{title:"2026 부산 폐업지원금·점포철거비 지원",description:"희망리턴패키지 점포철거비의 지원한도, 신청자격, 지원받을 수 없는 경우와 부산 폐업 소상공인 재취업 지원을 확인하세요.",url:"/support",type:"article"}};
const exclusions=[
["자가건물·무상임차","본인 소유 건물(일부 지분 포함)에서 영업했거나 무상 임차한 점포는 점포철거비 지원 대상에서 제외됩니다."],
["점포철거비 기수혜","점포철거비를 이미 지원받은 경우 주민등록번호 기준 1회 제한에 따라 다시 지원받을 수 없습니다."],
["주거용·가설·무허가 건축물","건축물대장상 주택·아파트 등 주거용이거나 가설·무허가 건축물은 원칙적으로 인정되지 않습니다. 공고상 일부 예외는 별도 확인이 필요합니다."],
["유사 철거지원 중복수혜","정부나 지자체의 유사한 점포철거 지원을 이미 받은 경우 중복 지원에서 제외되고, 사후 확인 시 환수될 수 있습니다."],
["단순 사업장 이전·동일장소 재창업","폐업이 아니라 사업장만 이전하거나, 지원금을 받은 뒤 동일 장소에 재창업하는 경우 제한됩니다."],
["지원제외 업종·비영리","희망리턴패키지 지원제외 업종, 비영리사업자·비영리법인은 지원 대상에서 제외됩니다."],
["자력철거·증빙 불충분","국세청 사업자등록 업체를 통하지 않은 자력철거는 지원되지 않습니다. 전자세금계산서·카드전표와 이체 등 공고가 요구하는 증빙도 준비해야 합니다."]
] as const;
const documents=["임대차계약서(임차인·목적물·기간·차임·전용면적 등 확인)","건축물대장","사업자등록증명원 또는 폐업사실증명원","소상공인 증빙서류","철거업체 공사내역서","전자세금계산서 또는 카드전표","이체확인증 또는 카드대금 완납 확인자료","철거 전·후 사업장 내·외부 사진"] as const;
export default function Page(){return <main className="page-shell"><style>{`
.support-hero-note{margin-top:18px;padding:14px 16px;border:1px solid #d8e5ff;background:#f6f9ff;border-radius:14px;color:#344054;font-size:14px}.support-stats strong{line-height:1.35}.support-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.support-card{padding:20px;border:1px solid #e4e9f2;border-radius:18px;background:#fff}.support-card h3{margin:0 0 8px;font-size:17px}.support-card p{margin:0;color:#667085;line-height:1.7}.support-card.warn{border-color:#f2d6c4;background:#fffaf7}.support-list{display:grid;gap:10px;padding:0;list-style:none}.support-list li{padding:13px 15px;border:1px solid #e4e9f2;border-radius:12px;background:#fff}.support-flow{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.support-flow div{padding:16px;border-radius:14px;background:#f6f8fb;border:1px solid #e4e9f2}.support-flow b{display:block;margin-bottom:6px;color:#2458d8}.support-source{font-size:13px;color:#667085;margin-top:14px}.support-source a{text-decoration:underline}.support-poster{border:1px dashed #b9c4d6;border-radius:20px;padding:18px;background:#f8fafc}.support-poster img{display:block;width:100%;max-width:760px;margin:0 auto;border-radius:12px}.support-poster figcaption{margin-top:12px;text-align:center;color:#667085;font-size:13px}@media(max-width:760px){.support-grid,.support-flow{grid-template-columns:1fr}.support-card{padding:17px}}`}</style>
<nav className="breadcrumb" aria-label="breadcrumb"><a href="/">홈</a><span>›</span><strong>2026 폐업지원</strong></nav>
<header className="list-hero"><div className="eyebrow-chip">2026 희망리턴패키지 · 부산 폐업지원</div><h1>폐업 철거비 최대 600만원,<br/><span className="gradient-text">누가 받을 수 있고 누가 제외될까?</span></h1><p>2026년 희망리턴패키지 원스톱폐업지원 공고를 기준으로 점포철거비 지원한도, 신청자격, 지원 제외 사례와 필요한 증빙을 정리했습니다. 부산에서 폐업 후 취업을 준비하는 경우 확인할 수 있는 별도 부산시 지원도 함께 안내합니다.</p><div className="cta-row"><a className="btn btn-primary" href={officialNotice} target="_blank" rel="noreferrer">소상공인24에서 신청 확인</a><a className="btn btn-glass" href={inquiryUrl}>철거 현장견적 문의</a></div><p className="support-hero-note">중요: ‘최대 600만원’은 폐업자에게 일괄 지급되는 현금지원금이 아닙니다. 인정되는 점포철거·원상복구 비용을 정해진 한도 안에서 심사·정산하는 제도입니다.</p></header>
<section className="support-box"><span className="section-kicker">2026 OFFICIAL STANDARD</span><h2>2026 점포철거비 핵심 기준</h2><div className="support-stats"><div><span>면적별 한도</span><strong>전용면적 3.3㎡당 20만원 이내</strong></div><div><span>최대한도</span><strong>2025.7.11 이후 폐업 최대 600만원</strong></div></div><p>2023.1.1~2025.7.10 폐업자는 최대 400만원, 2025.7.11 이후 폐업자는 최대 600만원 기준입니다. 부가가치세는 지원하지 않고 전자세금계산서상 공급가액을 기준으로 하며, 국세청에 사업자등록된 업체를 통한 철거가 필요합니다.</p><p className="support-source">기준: 2026년 희망리턴패키지 원스톱폐업지원 공고 · 신청기간은 2026년 1월부터 예산 소진 시까지로 안내되어 있으므로 신청 시점의 모집상태를 다시 확인하세요.</p></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">ELIGIBILITY</span><h2>점포철거비를 신청하려면</h2></div><p>공고일 기준 요건을 모두 충족해야 하며, 실제 선정·지급 여부는 제출서류 심사와 현장 확인 등에 따라 결정됩니다.</p></div><div className="support-grid"><article className="support-card"><h3>폐업(예정) 소상공인</h3><p>기폐업자는 원칙적으로 2023년 1월 1일 이후 폐업자이며, 폐업예정자는 정산 단계에서 폐업사실증명원을 제출할 수 있어야 합니다.</p></article><article className="support-card"><h3>60일 이상 사업 운영</h3><p>기폐업자는 개업일부터 폐업일까지, 폐업예정자는 개업일부터 신청일까지 사업 운영기간이 60일 이상이어야 합니다.</p></article><article className="support-card"><h3>유상 임차 사업장</h3><p>유상 임대차로 사업장을 운영하고 임대차계약서를 제출할 수 있어야 합니다.</p></article><article className="support-card"><h3>지원제외 업종이 아닐 것</h3><p>희망리턴패키지의 지원제외 업종에 해당하지 않아야 합니다. 여러 업종을 영위하면 공고 기준에 따라 주된 업종을 판단합니다.</p></article></div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">WHO CANNOT RECEIVE</span><h2>폐업 철거비를 받을 수 없는 대표적인 경우</h2></div><p>‘폐업했다’는 사실만으로 지원되는 것이 아닙니다. 아래 항목은 2026 공고에서 특히 먼저 확인할 제외조건입니다.</p></div><div className="support-grid">{exclusions.map(([title,text])=><article className="support-card warn" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">PAYMENT EXAMPLE</span><h2>600만원을 모두 받는 것은 아닙니다</h2></div><p>실제 지급액은 인정 면적에 따른 한도, 인정되는 공급가액, 폐업일별 최대 한도 등을 함께 적용해 결정됩니다.</p></div><div className="support-grid"><article className="info-card"><h3>예: 전용면적 10평</h3><p>면적 기준만 보면 10평 × 20만원 = 최대 200만원 범위입니다. 실제 인정비용이 이보다 적다면 인정된 비용 범위에서 심사됩니다.</p></article><article className="info-card"><h3>예: 전용면적 30평</h3><p>면적 기준은 600만원이지만 실제 인정 가능한 철거·원상복구 공급가액과 폐업일 기준 최대한도를 넘을 수 없습니다.</p></article></div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">DOCUMENT CHECK</span><h2>철거 전부터 남겨야 할 증빙</h2></div><p>지원 신청을 생각한다면 공사비뿐 아니라 계약서·결제·사진 증빙을 처음부터 맞추는 것이 중요합니다.</p></div><ul className="support-list">{documents.map(x=><li key={x}>{x}</li>)}</ul><p className="support-source">공고는 철거 전·후 내·외부 사진을 요구하며, 공사내용 식별을 위해 가능하면 동일 위치·동일 각도 촬영을 권고합니다. 현금거래는 정산 증빙으로 인정되지 않는다고 안내합니다.</p></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">APPLICATION FLOW</span><h2>철거 예정이라면 이 순서로 확인하세요</h2></div><p>지원 가능성을 확인하기 전에 공사를 먼저 끝내기보다 신청요건과 증빙방법을 먼저 확인하는 편이 안전합니다.</p></div><div className="support-flow"><div><b>01</b>소상공인24에서 최신 모집상태·공고 확인</div><div><b>02</b>소상공인·임차·운영기간·제외조건 확인</div><div><b>03</b>철거 전 사진과 임대차·원상복구 범위 정리</div><div><b>04</b>등록 철거업체 공사 후 세금계산서·이체·전후사진 등 정산자료 제출</div></div></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">BUSAN 2026</span><h2>부산에서는 폐업 후 재취업 지원도 별도로 확인하세요</h2></div><p>부산시는 2026년 폐업 소상공인의 고용전환 촉진 사업을 안내했습니다. 2026년 4월 부산시 보도자료에는 취업에 성공한 폐업 소상공인의 자산형성을 돕는 ‘희망두배통장’ 최대 180만원 지원과, 폐업 소상공인을 채용한 기업에 1인당 최대 360만원의 고용인센티브가 안내됐습니다. 해당 공고의 접수기간은 종료될 수 있으므로 현재 추가모집 여부는 부산시·부산일자리정보망에서 확인해야 합니다.</p><div className="cta-row"><a className="btn btn-glass" href={busanEmployment} target="_blank" rel="noreferrer">부산시 폐업 후 취업지원 자료</a><a className="btn btn-glass" href={busan2026} target="_blank" rel="noreferrer">2026 부산 소상공인 지원자료</a></div></section>
<section className="section"><div className="section-heading"><div><span className="section-kicker">REFERENCE IMAGE</span><h2>희망리턴패키지 지원내용 한눈에 보기</h2></div><p>사용자가 제공한 안내 이미지를 넣을 자리입니다. GitHub에 아래 파일명으로 업로드하면 페이지에 바로 표시되도록 구성했습니다.</p></div><figure className="support-poster"><img src="/images/support/hope-return-package-2026.png" alt="희망리턴패키지 원스톱폐업지원 취업지원 재기사업화 지원 안내" loading="lazy"/><figcaption>예정 이미지 경로: /public/images/support/hope-return-package-2026.png</figcaption></figure></section>
<section className="section soft-section"><div className="section-heading"><div><span className="section-kicker">OFFICIAL LINKS</span><h2>신청 전 공식자료를 다시 확인하세요</h2></div><p>정책은 예산·수정공고에 따라 달라질 수 있습니다. 특히 신청기간과 접수 가능 여부는 방문 시점의 공식 화면이 최종 기준입니다.</p></div><div className="cta-row"><a className="btn btn-primary" href={officialNotice} target="_blank" rel="noreferrer">소상공인24</a><a className="btn btn-glass" href={hopeUrl} target="_blank" rel="noreferrer">희망리턴패키지</a><a className="btn btn-glass" href={bukguReference} target="_blank" rel="noreferrer">부산 북구 참고자료</a></div></section>
<section className="final-cta"><div><span className="section-kicker">DEMOLITION PREP</span><h2>지원요건을 확인했다면<br/>철거범위와 증빙계획을 함께 준비하세요.</h2><p>현장 위치, 전용면적, 임대차 원상복구 범위와 사진을 준비하면 철거 견적을 더 구체적으로 확인할 수 있습니다.</p></div><div className="cta-row"><a className="btn btn-light" href={inquiryUrl}>무료 현장견적 문의</a><a className="btn btn-glass" href="/guide/demolition-estimate-checklist">견적 체크리스트</a></div></section>
</main>}